### ISSUE TITLE
Put the more detailed goals of the project in the description

### ISSUE THREAD

**Issue by jan-kleks** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#10]
I mean [the things that Smokemonster mentioned when he was being interviewed by RetroRGB](https://www.youtube.com/watch?v=xnDvFr6Lpqo&t=1121s).

**Comment by frederic-mahe** [comment]
@jan-kleks the first sentence of the README says:

> The goal of the project is to allow users to build their own packs, based on suggested files and folder layouts compiled by SmokeMonster or other creators.

What would you suggest to add to make the goal clearer and more comprehensive? Maybe something about the scope?

> A SMDB is meant as an archivist project, listing and classifying all the games or programs that can run on a given hardware (genuine or clone), including official games but also after-market games, hacks, demos and homebrews.

@SmokeMonsterPacks what do you think?

**Comment by jan-kleks** [comment]
@frederic-mahe Yeah, defining the scope would be nice. I think you're on the right track with that new suggested description frederic-mahe.

**Comment by SmokeMonsterPacks** [comment]
Thanks for reminding me to this. I just updated the goals, what do you think?

**Comment by jan-kleks** [comment]
@SmokeMonsterPacks Nice! The question is whether the name "EverDrive Packs" still fits the scope of the project... Maybe you should think about something more universal?

**Comment by SmokeMonsterPacks** [comment]
Oh, I have thought long and hard about that for the last few years, but EverDrive Packs is what the project is named and I won't be changing it just because I'd essentially be losing the "branding" that is so familiar to everyone.
