### ISSUE TITLE
Please Add Roll-chan 1-6 (NES), Roll-chan World 1-5 (GB) & Roll-chan Mini World (GG) to the Everdrive Packs.

### ISSUE THREAD

**Issue by ghost** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#100]
I'm Only Here cause i Want the Roll-chan 1-6 (NES), Roll-chan World 1-5 (GB) & Roll-chan Mini World (GG) on the Everdrive Packs.

**Comment by pyrfiller** [comment]
Also Please Add Roll-chan - The Wily Wars (MD) (When it get's Released) & Roll-chan no Constancy (NES).

**Comment by pyrfiller** [comment]
FIRST OFF, Add All, Classic/MM1, MM8 & MM11 Roll-chan.
Note MM11 Roll-chan isn't currently Available on Roll-chan 1-6 (NES) & Roll-chan World 1-5 (GB).

**Comment by pyrfiller** [comment]
Patch Both Japan & USA Versions.

**Comment by pyrfil** [comment]
Roll-chan Patch Links
https://www.romhacking.net/hacks/1704/
https://www.romhacking.net/hacks/2265/
https://www.romhacking.net/hacks/2266/
https://www.romhacking.net/hacks/2799/
https://www.romhacking.net/hacks/2267/
https://www.romhacking.net/hacks/2691/
https://www.romhacking.net/hacks/2692/
https://www.romhacking.net/hacks/3070/
