### ISSUE TITLE
ColecoVision cleaning

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#101]
* compare SMDB with No-Intro
  * missing in SMDB
  * in SMDB but not in No-Intro
* check Choplifter https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/issues/1

**Comment by tjanas** [comment]
BAD NAME:
> BC's Quest for Tires (1983)(Coleco Canada).bin
> should be
> BC's Quest for Tires (Coleco Canada).col
>
> BC's Quest for Tires II - Grog's Revenge (1984)(Coleco Canada).bin
> should be
> BC's Quest for Tires II - Grog's Revenge (Coleco Canada).col
> 
> Evolution (1983)(Coleco Canada).bin
> should be
> Evolution (Coleco Canada).col

MISSING:
> Dam Busters, The (Coleco Canada).col
> Miner 2049er Starring Bounty Bob (USA, Europe) (v1.1).col

BAD CHECKSUM AND BAD NAME:
> "Miner 2049er Starring Bounty Bob (USA).col" (71d1bd4d)
> should be
> "Miner 2049er Starring Bounty Bob (USA, Europe).col" (f37af58c)
>
> "From Out of the Jungle - Tarzan (USA).col" (eff35a70)
> should be
> "Tarzan (USA, Europe).col" (7CD7A702)

CHECKSUM DOES NOT MATCH NOINTRO:
> Activision Decathlon, The (USA).col
> Alcazar - The Forgotten Fortress (USA).col
> Aquattack (USA).col
> Artillery Duel (USA).col
> Beamrider (USA).col
> Blockade Runner (USA).col
> Boulder Dash (USA).col
> Buck Rogers - Planet of Zoom (USA, Europe).col
> Bump 'N' Jump (USA, Europe).col
> Cabbage Patch Kids - Adventures in the Park (USA, Europe).col
> Cabbage Patch Kids Picture Show (USA, Europe).col
> Campaign '84 (USA).col
> Carnival (USA, Europe).col
> Choplifter (USA, Europe).col
> Chuck Norris - Super Kicks (USA).col
> Congo Bongo (USA, Europe).col
> Cosmic Avenger (USA, Europe).col
> Dam Busters, The (USA, Europe).col
> Dance Fantasy (USA).col
> Defender (USA).col
> Evolution (USA).col
> Facemaker (USA).col
> Fathom (USA).col
> Flipper Slipper (USA).col
> Fraction Fever (USA).col
> Frenzy (USA, Europe).col
> Frogger (USA).col
> Frogger II - ThreeeDeep! (USA).col
> Galaxian (USA).col
> Gateway to Apshai (USA).col
> Gust Buster (USA).col
> Gyruss (USA).col
> Heist, The (USA).col
> James Bond (USA).col
> Juke Box (USA).col
> Jungle Hunt (USA).col
> Keystone Kapers (USA).col
> Linking Logic (USA).col
> Logic Levels (USA).col
> Memory Manor (USA).col
> Meteoric Shower (USA).col
> Monkey Academy (USA, Europe).col
> Montezuma's Revenge (USA).col
> Moonsweeper (USA).col
> Motocross Racer (USA).col
> Mountain King (USA).col
> Mousetrap (USA, Europe).col
> Mr. Do!'s Castle (USA).col

**Comment by tjanas** [comment]
BAD CHECKSUM AND BAD NAME:
> "Pitstop (USA).col" (1e455299)
> should be
> "Pitstop (USA, Europe).col (81be4f55)

MISSING:
> "Pitstop (USA).col" (e627fcf0) Note: this ROM was found only in Imagic cart shells, different than the other "USA, Europe" variant
> "Victory (Europe).col" (B1FDA1C5)
> "Victory (USA).col" (70142655)

BAD DUPLICATE IN SMDB:
> Remove "Sector Alpha (USA).col" from SMDB
> and rename "Sector Alpha (USA) 2K Restored Ikrananka.bin" to "Sector Alpha (USA).col"

NOT IN NO-INTRO:
> "Victory (USA, Europe).col"

CHECKSUM DOES NOT MATCH NOINTRO:
> Nova Blast (USA).col
> Omega Race (USA, Europe).col
> One on One (USA).col
> Pitstop (USA).col
> Popeye (USA).col
> Q-Bert's Qubes (USA).col
> Quest for Quintana Roo (USA).col
> Robin Hood (USA).col
> Roc 'N Rope (USA, Europe).col
> Rock 'N' Bolt (USA).col
> Rolloverture (USA).col
> Sewer Sam (USA).co
> Sir Lancelot (USA).col
> Skiing (USA).col
> Slurpy (USA).col
> Smurf Paint 'n Play Workshop (USA, Europe).col
> Spectron (USA).col
> Squish 'Em Sam! (USA).col
> Star Trek (USA, Europe).col
> Subroc (USA, Europe).col
> Super Cobra (USA).col
> Super Cross Force (USA).col
> Tank Wars (USA).col
> Tournament Tennis (USA).col
> Tutankham (USA).col
> War Games (USA, Europe).col
> War Room (USA).col
> Wing War (USA).col
> Word Feud (USA).col

**Comment by tjanas** [comment]
As some sanity check, here are some that DO match no-intro:
> 2010 - The Graphic Action Game (USA, Europe).col
> Antarctic Adventure (USA, Europe).col
> BurgerTime (USA, Europe).col
> Centipede (USA).col
> H.E.R.O (USA).col
> Mr. Do! (USA, Europe).col
> Pitfall! (USA).col
> River Raid (USA).col
> Zaxxon (USA, Europe).col

**Comment by maniac79** [comment]
Please review Pull Request #181 - I think I managed to correct all the wrong hashes and file names for all main folders.
I also moved some files around (e.g. there were Hacks in the Licensed folders, etc).

Although there's one open issue (kind of big one though):
All hashes/names in _4 Game Series Collections/*_ have to be revised as well...

**Comment by frederic-mahe** [comment]
Thanks @maniac79 I've created a new issue for the Game Series Collections.

**Comment by tjanas** [comment]
Thank you for fixing these!
