### ISSUE TITLE
Compatability/Hash check for Insector X (Famicom)

### ISSUE THREAD

**Issue by Jayde6** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#103]
Can someone double check if:

`5f30f8abb7749bbe3132c690b627e7299bdf9dbc17e3e72ae734dc563542a33c	EverDrive N8/2 Japan - A-Z/Japan E-J/Insector X (Japan).nes	9648bd6e381673e52e76c1476d30df063d51b076	26e5ada9fbac3137a94096bd5b0638ca	7dab812d`

is the correct/good hash?

The stage 1 boss has corrupted graphics on the Nt Mini JB. If it is correct and works with EverDrive and PowePak, then it's an issue with the Nt Mini and can be reported to Analogue's support, and can be moved to unsupported in the Nt Mini Jailbreak SMDB.

**Comment by tjanas** [comment]
Confirmed to be a bad dump. It does not match no-intro. The correct dump should have a crc32 of f80bdc50

**Comment by Jayde6** [comment]
Thanks for looking into it @tjanas , do you know if that's with or without a header? The one in the smdb has a header.

**Comment by tjanas** [comment]
Looks like the no-intro copy with the checksum of f80bdc50 does not have the 16 byte header. When I stripped the NES header from the copy in the SMDB pack, it matches f80bdc50. So it looks like that is not the issue.

**Comment by Jayde6** [comment]
Thanks again for checking and going the extra mile in testing out the header thing. Maybe it can be fixed with an edit to the header like some of the games that require a sub header, but for now it looks like it's unsupported by the nt mini jb.

**Comment by frederic-mahe** [comment]
I am going to close that issue, feel free to reopen it if need be.
