### ISSUE TITLE
Wrong sorting for some games inside the Turbo EverDrive & Super SD System 3 (Game Series Collection/Genre/Shoot 'em Up)

### ISSUE THREAD

**Issue by loloC2C** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#106]
Hello, 

I have found the following games inside the Game Series Collections/Genre/Shoot 'em Up/Sort By - Veritical View folder that would belong to the Horizontal View:

Barunba (Japan).pce
Bouken Danshaku Don - The Lost Sunheart (J) T-Eng Test 2 toktogu.pce
Coryoon - Child of Dragon (Japan).pce
Dead Moon (USA).pce
Gokuraku! Chuuka Taisen (Japan).pce
Hana Taaka Daka! (Japan).pce
Magical Chase (USA).pce
Ordyne (USA).pce
Paranoia (Japan).pce
Power Gate (Japan).pce
Psychosis (USA).pce
Rabio Lepus Special (Japan).pce
Rock-On (Japan).pce
Sinistron (USA).pce
Violent Soldier (Japan).pce
W-Ring - The Double Rings (Japan).pce

**Comment by frederic-mahe** [comment]
thanks @loloC2C fixed in 22cc535a1b8f09b99f95b67fb1b16904f778ebf8
