### ISSUE TITLE
Duplicates with bad file names (a leading space) in Mega EverDrive SMDB

### ISSUE THREAD

**Issue by xtcrefugee** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#107]
I noticed that I was two files short after copying from my NTFS drive to a FAT32 SD card, it looks like there are two duplicate files in the list that begin with a space:

```
34dd31bc060c948420e054a9f57432378b38eabfd8cdd88ed37a41d3c4a757b8	Mega EverDrive/4 Homebrew/Demos & Intros/ Demo (PD) Limp Ninja 2017-5.bin	180f5a62b759e2e98d78b9c8608ba0aad6942c60	f5f728794cbf7cd100da14c61ad461f1	72470a77
7c93587ef065ea839a62544b8bfcbb0e278fee00973e6364b48e6f48e88a0e89	Mega EverDrive/4 Homebrew/Demos & Intros/ Intro (PD) Sundown 2016 SOS-Party.bin	58dcca30d599fc5e57d7083a9db53b871289fb21	6576a83c3fdb1f0f7636a2499fbcd0a5	6187cc3b
```

Also "Cave Story MD (PD) 0.5.1a andwn" is outdated, there's a version 0.5.2 now, see https://github.com/andwn/cave-story-md/releases
If you're still adding new free homebrew titles to these packs, can I recommend Old Towers, it's a really nicely polished game IMHO: https://retrosouls.itch.io/old-towers

Many, many thanks for continuing to maintain these packs, SmokeMonster!

**Comment by tjanas** [comment]
Regarding the Old Towers homebrew, there is a newer version (1.2), vs the older version in Mega Everdrive SMDB 7.1.

**Comment by xtcrefugee** [comment]
1.2 is actually in SMDB 7.1 twice, as _Old Towers (PD) RetroSouls v1.2.md_ and _Old Towers (PD) v1.2 RetroSouls.md_
v1.0 doesn't seem to be available for download any more, so it's not possible to 100% SMDB 7.1 unless you already had a copy. Going forward, that may be an issue for all games distributed through itch.io I guess.

**Comment by frederic-mahe** [comment]
fixed in https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/b6ac44de65f4380b4fb5c3942711973d4cac04f8

**Comment by tjanas** [comment]
Shouldn't we keep the newer version (1.2) and remove the old version (1.0), instead of vice-versa?

**Comment by frederic-mahe** [comment]
We still have one v1.2 entry, I removed an extra v1.2 (see line 8044).
