### ISSUE TITLE
Mega Pack: update SOR2 International Action Heroes hack versions from 1.54 to 1.55

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#109]
Version 1.55 fixes a glitch present in 1.54. Currently, the latest version of the Mega Everdrive contains version 1.54. Patch for version 1.54 is no longer available. https://www.romhacking.net/hacks/3977/

Name: SOR2 International Action Heroes Enter the Dragon v1.55 Dha Lau Hoo.md
Size: 2556000 bytes (2496 KiB)
SHA1: 5EBCE6D214B287CAEFA6CC47035452151145ABD1

Name: SOR2 International Action Heroes The Game of Death v1.55 Dha Lau Hoo.md
Size: 2556000 bytes (2496 KiB)
SHA1: 3868C9B36EF88839D2674A8F89400718619FD325

**Comment by frederic-mahe** [comment]
@tjanas would it be possible for you to submit a pull request for that?

**Comment by maniac79** [comment]
Pull Request #159

**Comment by frederic-mahe** [comment]
fixed by @maniac79 in 2b9bf9a0bdbb272405fccd70231cedbdc82ee4e0
