### ISSUE TITLE
Have you thought about some kind of a versioning/releases scheme (plus possibly a changelog for new game content/new features of the tools)?

### ISSUE THREAD

**Issue by jan-kleks** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#11]

**Comment by frederic-mahe** [comment]
Tool features should not change that much from now on. Regarding the packs, now that the file format is stable, the fine scale changes can be seen using GitHub's diff function. And I believe SmokeMonster will keep on posting summarized changelogs on the forums.
