### ISSUE TITLE
Mega Pack: rename Pinocchio (Europe) (Proto) (1995-06-12).32x

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#110]
According to [hiddenpalace](https://hiddenpalace.org/Pinocchio_32x_(Dec_6,_1995_prototype)), this prototype was released on the 6th day of December 1995. The file should be named "Pinocchio (Europe) (Proto) (1995-12-06).32x"

**Comment by frederic-mahe** [comment]
fixed in https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/227de0d12c77161c34f2cdb47b392cd102148abd thanks!
