### ISSUE TITLE
Mega EverDrive: Chase (PD) v2 Jack Nolddor.md checksum mismatch?

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#111]
The crc32 listed is 0b3426ed, but if I obtain the version of this [rom](https://gitlab.com/nolddor/chase-md/blob/master/out/rom.bin) directly from [developer Jack Nolddor](https://gitlab.com/nolddor/chase-md), its crc32 is fdea825e.

**Comment by frederic-mahe** [comment]
Let's wake up the Smoke Monster and close some issues! Thanks @tjanas for reporting all these little discrepancies.

**Comment by maniac79** [comment]
@tjanas is right and I would like to fix it.
If you read this in time you can maybe re-assign to me, @frederic-mahe. I'll probably submit a fix tomorrow.

**Comment by tjanas** [comment]
I can probably submit the pull request tonight.

**Comment by maniac79** [comment]
I'm already on it...
Tbh I'm very new to Git/GitHub, I am still learning how to do it as I go...
I have already done the change, just need to create the PR.

**Comment by frederic-mahe** [comment]
fixed in https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/1475a43c614a9900a52ef62e8713b86dce35b038

thanks @maniac79 , thanks @tjanas
