### ISSUE TITLE
Virtual Boy SMBD: padded rom in unpadded directory

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#113]
The following file should have its padding removed and be renamed appropriately:
`\unpadded\4 Translations\SD Gundam English (J) T+Eng v1 Ben & Greg Stevens_pad.vb`

**Comment by frederic-mahe** [comment]
@tjanas what is that padding and how can it be removed?

**Comment by frederic-mahe** [comment]
fixed by @tjanas in e5345c776c38e4c7128a08228a2f4096a84f33ec
