### ISSUE TITLE
Taekwon-Do (Korea): same name, different hash values

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#116]
There is an entry in SmokeMonster's pack for the SNES with the MD5 hash d41d8cd98f00b204e9800998ecf8427e and the name *Taekwon-Do* (Korea). This is probably a misnamed ROM, as it seems to correspond to a bad dump of *Mario to Wario* (see https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/issues/142).

```
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855	SD2SNES/1 US - T-Z/Taekwon-Do (Korea).sfc	da39a3ee5e6b4b0d3255bfef95601890afd80709	d41d8cd98f00b204e9800998ecf8427e	0
3438e5d96d4b58da6f6439b836f44aac57b24f75910322b86f4f9fd3adb70e81	SD2SNES/2 Japan - A-Z/Japan T-Z/Taekwon-Do (Japan) (Ja,Ko).sfc	dc61cb9b82eb58a9b09cb93a10b6731eaa4cd053	e9eb2c3d0b6e21baafbfc4b614e04a3f	93f29dde
1bb9ba72dfec638ed4cc7c721e31fde2f3e08d160b266a62b6e3997f711cf7cd	SD2SNES/2 Other Regions - A-Z/Other Regions/Taekwon-Do (Korea).sfc	11826edddb9d8e2a0267bf8d5d96b343191c6511	4c9dc70fd849a41644c81a0ffc8dee11	d20d7701
3438e5d96d4b58da6f6439b836f44aac57b24f75910322b86f4f9fd3adb70e81	SD2SNES/4 Game Series Collections/Genre/Fighting/Japan & Europe Exclusives/Fighting - Japan Exclusives (Needs Translating)/Taekwon-Do (Japan) (Ja,Ko).sfc	dc61cb9b82eb58a9b09cb93a10b6731eaa4cd053	e9eb2c3d0b6e21baafbfc4b614e04a3f	93f29dde
```

**Comment by tjanas** [comment]
Here are some of my initial findings:

There are two entries at no-intro:

Taekwon-Do (Korea): https://datomatic.no-intro.org/?page=show_record&s=49&n=2966
CRC32: D20D7701

Taekwon-Do (Japan) (Ja,Ko): https://datomatic.no-intro.org/?page=show_record&s=49&n=2965
CRC32: 93F29DDE

One is listed as the parent ROM of the other. The ROM with checksum D20D7701 is a verified dump by two contributors, including byuu.

The other appears to be an old GoodSNES scene-dump ROM that was modified to remove an intro that was hacked in.

I found this GoodSNES ROM in an old Everdrive pack:
Super EverDrive & SD2SNES Japan Add-On 2018-08-25\2 Japan - A-Z\Japan T-Z\

I found the other one in the following:
Super EverDrive, SD2SNES, Super NT Pack v6.2\2 Other Regions - A-Z\Other Regions\

I diff'd the roms in a hex editor and they seem to be unique to each other. I also loaded each of them in an emulator and they have obvious differences (93F29DDE has two language menu options presented in English text: Japanese or Korean, D20D7701 appears to be Korean only).

![Taekwon-Do (Korea)](https://user-images.githubusercontent.com/20304619/78690059-9b206e00-78bc-11ea-8b7c-1b6f1f2ea2a9.png)
![Taekwon-Do (Japan) (Ja,Ko)](https://user-images.githubusercontent.com/20304619/78690063-9c519b00-78bc-11ea-8b79-f080b831e504.png)

I believe the SMDB entries should be the following (and it may already be correct):
```
3438e5d96d4b58da6f6439b836f44aac57b24f75910322b86f4f9fd3adb70e81	SD2SNES/2 Japan - A-Z/Japan T-Z/Taekwon-Do (Japan) (Ja,Ko).sfc	dc61cb9b82eb58a9b09cb93a10b6731eaa4cd053	e9eb2c3d0b6e21baafbfc4b614e04a3f	93f29dde
1bb9ba72dfec638ed4cc7c721e31fde2f3e08d160b266a62b6e3997f711cf7cd	SD2SNES/2 Other Regions - A-Z/Other Regions/Taekwon-Do (Korea).sfc	11826edddb9d8e2a0267bf8d5d96b343191c6511	4c9dc70fd849a41644c81a0ffc8dee11	d20d7701
```

The following should be removed
`SD2SNES/1 US - T-Z/Taekwon-Do (Korea).sfc`

**Comment by frederic-mahe** [comment]
Nice detective work @tjanas I removed the file (see 322055b329ee1fe09504c78c858549a918593ce0). 

Maybe we can get someone in the community to dump and verify the other entry (93F29DDE)? @SmokeMonsterPacks do you now someone that could own a cartridge of the Super Famicom game Taekwon-Do?

https://datomatic.no-intro.org/?page=show_record&s=49&n=2965
