### ISSUE TITLE
Building Pack For SuperNT

### ISSUE THREAD

**Issue by Endgame22** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#119]
I assume I want to Build a pack since the Super NT Jailbreak SMDB exists? 

I enter this code in python and it says Syntax Error. Anyone see what I did wrong? Also not sure what missing.txt is, do I have to create it or is it made automatically? 

I'm trying to follow the instructions but it's not working, I can't find any tutorial online. 

"C:\\Users\\timus\_000\\Documents\\Games\\SuperNT\\build\_pack.py" -i "C:\\Users\\timus\_000\\Documents\\Games\\SNES" -d "C:\\Users\\timus\_000\\Documents\\Games\\SuperNT\\EverDrive Pack SMDBs\\NT Jailbreak SMDB.txt" -o "C:\\Users\\timus\_000\\Documents\\Games\\Everdrive Build Pack" -m "C:\\Users\\timus\_000\\Documents\\Games\\Everdrive Build Pack\\Missing.txt"

**Comment by FiZiX** [comment]
Try running from the command-line, like this:

`python "C:\Users\timus_000\Documents\Games\SuperNT\build_pack.py" -i "C:\Users\timus_000\Documents\Games\SNES" -d "C:\Users\timus_000\Documents\Games\SuperNT\EverDrive Pack SMDBs\NT Jailbreak SMDB.txt" -o "C:\Users\timus_000\Documents\Games\Everdrive Build Pack" -m "C:\Users\timus_000\Documents\Games\Everdrive Build Pack\Missing.txt"`

Missing.txt will be created automatically with a list of files that are missing from your build.

**Comment by Endgame22** [comment]
So add python to command line?

**Comment by FiZiX** [comment]
> So add python to command line?

Yes. You said you were entering the command in python. Try running it from the command line with the python command in front.

**Comment by Endgame22** [comment]
Still saying syntax error. I also put the path for python program in front of command line instead and that said unexpected character after line continuation error

**Comment by frederic-mahe** [comment]
On Windows, depending on your python installation, you may need to begin your command with the location of `python.exe` (for example, `C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\python.exe`).

**Comment by Endgame22** [comment]
Thats what i'm referring to in the previous comment, I entered the location of where i have python.exe installed first and then the rest

**Comment by frederic-mahe** [comment]
Could you please copy-paste the command and the error message you get?

**Comment by Endgame22** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/54992644/64480306-96f36d00-d182-11e9-996a-bbd484fa5d96.png)

C:\Program Files\Python36\python.exe "C:\Users\timus_000\Documents\Games\SuperNT\build_pack.py" -i "C:\Users\timus_000\Documents\Games\SNES" -d "C:\Users\timus_000\Documents\Games\SuperNT\EverDrive Pack SMDBs\NT Jailbreak SMDB.txt" -o "C:\Users\timus_000\Documents\Games\Everdrive Build Pack" -m "C:\Users\timus_000\Documents\Games\Everdrive Build Pack\Missing.txt"

Syntax Error: unexpected character after line continuation character

**Comment by frederic-mahe** [comment]
Hi, you seem to be running the build_pack command from a python interpreter. You should use Windows' command line instead (CMD).

**Comment by Endgame22** [comment]
Ahhhh I see.
 I tried and it seems to be stuck at 0.0%, not sure if it just takes a long time or if something else is wrong.

**Comment by frederic-mahe** [comment]
Hum, the script supports zipped archived (a zip file containing files). However, it is not designed to work on zipped archived containing zipped files. Could you please try to unzip a few ROMs to a test folder and use that test folder as your input `-i` folder?

**Comment by Endgame22** [comment]
Same issue is happening

**Comment by frederic-mahe** [comment]
It seems Windows is mixing Unix and DOS filepath formats. I've just pushed a commit https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/19634c15bfd534080612563be7d1b1afa27ff921 to try to fix that issue. Could you please try it? Relaunching the same command line should be OK.

If that does not work, I recommend to try https://github.com/fartwhif/GammaCopy as it is designed specifically for Windows.

**Comment by Endgame22** [comment]
Do I have to redownload this database first?

**Comment by frederic-mahe** [comment]
Just the build_pack.py script, but you can redownload the whole repository if you want: https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/archive/master.zip

**Comment by Endgame22** [comment]
Yay, progress! It processed the 3565 roms and says coverage: 6932/10209 (67.9%). Not sure what that means exactly, whether it only completed 67% or if it refers to something else. 

To put this on to my jailbroken SuperNT, do I just drop the created SD2SNES folder on the sd card root and I'm good to go, or do I need to put it in another folder on root?

Also if I want to add more roms can i drop them in to whatever folder it needs to or do I need to use cmd again?

**Comment by frederic-mahe** [comment]
> coverage: 6932/10209 (67.9%)

that means that you are missing a couple thousand ROMs to get a complete set as described by SmokeMonster. Usually, the missing ROMs are hacks and obscure things. You probably have all the official and most current ROMs. The `-m` option creates a file for you with a list of what's missing.

If you want to add ROMs to SD2SNES, just add them to the folder wherever you want. But you can also group the new ROMs in a tmp folder, run the same command again using that tmp folder as input `-i`, and the script will place the new ROMs for you in the SD2SNES folder (if the ROMs are part of the SmokeMonster database).

If you want to transfer that to a SD card for a Super Nt, rename `SD2SNES` to `SNES` and place it at the root of your SD card.

**Comment by Endgame22** [comment]
Everything is working now, thank you so much. I won't close this case yet in case there are more problems that arise
