### ISSUE TITLE
Game description format: extensive game categories, filters and rules for creating custom folders

### ISSUE THREAD

**Issue by jan-kleks** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#12]
I can see that Smoke Monster put a lot of effort to create his own "filter folders" (genre, best games, etc.) by hand, however, maybe instead of connecting categories to folders, these various categories could be attached to game checksums, allowing for adding even more categories, and then letting users create their own unique favorite folder structures, and to easily remove the games they don't need. Maybe a game database, for instance, [MobyGames' categories (on the left, click on "view complete list" to see even more categories)](http://www.mobygames.com/browse/games) could be used as a basis for these extensive filtering options, or we may ask users in what new categories they would be interested the most. Possibly other ROM preservation projects would like to get involved in the creation of some kind of a meta "game description format" for advanced filtering (maybe even FPGA devices could use a such a description format natively in the future)? 

Anyway, here's an example how a tool with such an advanced feature could work :

1) Create a folder structure based on genre

2) Remove sport games

3) Remove erotic games

4) Inside this genre folder structure create "letter folders" (A-E, F-M, etc.)

5) Remove all NTSC-J games that have an NTSC-US equivalent except games that are censored (green blood, for example) in the NTSC-US version  

6) Remove all PAL games, except for PAL exclusives, and games that have no English NTSC-US translation

I hope you understand my idea...

EDIT: Maybe some technical information (not present in the ROM file header) could be put into such a description format too (for use with FPGAs/emulators to turn on/off certain emulation features)?

**Comment by SmokeMonsterPacks** [comment]
Thanks. That is a great idea. I'd rather leave the collections as they are though. It's just easier to manage.
