### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by DhinCardoso** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#120]
Since the last **build_pack.py** I'm getting this error:

```
C:\WINDOWS\system32>"D:\SMM\EverDrive-Packs-Lists-Database-master\build_pack.py" 
-i "E:\EverDrive\Super EverDrive & SD2SNES" 
-d "C:\Users\dhinc\SMM\SMDB.txt" 
-o "D:\SMM" 
-m "D:\SMM\Missing.txt"
Traceback (most recent call last):
  **File** "D:\SMM\EverDrive-Packs-Lists-Database-master\build_pack.py", line 257, in <module>
    FOUND_ENTRIES = parse_folder(SOURCE_FOLDER, DATABASE, OUTPUT_FOLDER)
  **File** "D:\SMM\EverDrive-Packs-Lists-Database-master\build_pack.py", line 168, in parse_folder
    hashes = get_hashes(filename)
  **File** "D:\SMM\EverDrive-Packs-Lists-Database-master\build_pack.py", line 230, in get_hashes
    with zipfile.ZipFile(filename, 'r') as z:
  **File** "C:\Users\dhinc\AppData\Local\Programs\Python\Python37-32\lib\zipfile.py", line 1225, in __init__
    self._RealGetContents()
  **File** "C:\Users\dhinc\AppData\Local\Programs\Python\Python37-32\lib\zipfile.py", line 1310, in _RealGetContents
    fp.seek(self.start_dir, 0)
**OSError: [Errno 22] Invalid argument**
```

**Result:**
- I don't know if the final folder was populated accordingly;
- The missing.txt was not created

**Comment by frederic-mahe** [comment]
thank you for reporting that bug @DhinCardoso 

I made a blind change to the `build_pack.py` script (see commit https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/19634c15bfd534080612563be7d1b1afa27ff921) that I was not able to test directly. Do you confirm that this change (and only this change) makes the script fail on your Windows machine?

If yes, I will revert the change.

**Comment by DhinCardoso** [comment]
In the next 30 minutes I'll do another test (if a manage to put my hands in my old **build_pack.py**)

**Comment by DhinCardoso** [comment]
Tried several times with versions all the way down to commit [512b9ae](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/512b9ae7a680684f658de9af7ad2b18ed51791a4) and still getting the exact same error, as long as **zipfile.py** was mentioned in the error log I deduced it could be the zip/7z support, so I rolled back to commits before the zip/7z support... but I guess it's something related with my system... because still getting the same **Error no 22**

I used the "Browse the repository at this point in the history" button on the right side on commit list, and downloaded the **build_pack.py**, is that correct?

**Comment by DhinCardoso** [comment]
**Some info:**
No compressed files at all in the **UNORGANIZED** folder;
Running _**cmd**_ in _**Admin**_ mode;
The **ORGANIZED** folder have more than 11k files in it (Looks pretty complete);
The script do not output the "missing.txt";

**Comment by DhinCardoso** [comment]
Holy crap!

I tried with another SMDB and worked O.O - Looks like the problem isn't in the **build_pack.py** after all.

I'll continue the combinations (old SMDBs with new build_pack.py) to manage the latest working SMDB.

**Tested OK:** SMDB for SD2SNES from commit 512b9ae on 25 Feb

_C:\WINDOWS\system32>"D:\SMM\SMDBS\build_pack.py" -i "D:\SMM\INPUT" -d "D:\SMM\SMDBS\SMDBs\SD2SNES.txt" -o "D:\SMM\OUTPUT" -m "D:\SMM\missing.txt"
processing file:     40367
coverage: 12981/13114 (98.99%)_

**Comment by DhinCardoso** [comment]
**Latest successful combination:**
Super EverDrive & SD2SNES SMDB.txt _master_ + **build_pack.py** 02608d0

**build_pack.py** tested returning Errno22
8cf6c9c 
e73d06f
a280c19
efc3a24
_master_

Looks like it's not the SMDB file since the latest update was last year, so kept trying build_packs from different versions, looks like the latest version working was from commit 02608d0 on 21 Jul

**Comment by frederic-mahe** [comment]
@DhinCardoso thanks for the detailed tests around this bug. I am a bit puzzled about what could cause the issue (maybe an issue with the filenames in your unorganized folder?). I have just pushed a new commit fixing a missing normalization of filenames (https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/74d7bc86b9c5cb1f75853e54c57cafc1f2288bc7).

Could you please try this new `build_pack.py` on the latest `Super EverDrive & SD2SNES SMDB.txt`?

**Comment by DhinCardoso** [comment]
**Same Error:**
```
"D:\SMM\BUILD 74d7bc8 Sep 25\build_pack.py"
-i "D:\SMM\INPUT"
-d "D:\SMM\SMDBs\Super EverDrive & SD2SNES SMDB.txt"
-o "D:\SMM\OUTPUT"
-m "D:\SMM\SD2SNES.txt"

Traceback (most recent call last):
  File "D:\SMM\BUILD 74d7bc8 Sep 25\build_pack.py", line 258, in <module>
    FOUND_ENTRIES = parse_folder(SOURCE_FOLDER, DATABASE, OUTPUT_FOLDER)
  File "D:\SMM\BUILD 74d7bc8 Sep 25\build_pack.py", line 169, in parse_folder
    hashes = get_hashes(filename)
  File "D:\SMM\BUILD 74d7bc8 Sep 25\build_pack.py", line 231, in get_hashes
    with zipfile.ZipFile(filename, 'r') as z:
  File "C:\Users\dhinc\AppData\Local\Programs\Python\Python37-32\lib\zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "C:\Users\dhinc\AppData\Local\Programs\Python\Python37-32\lib\zipfile.py", line 1310, in _RealGetContents
    fp.seek(self.start_dir, 0)
OSError**: [Errno 22] Invalid argument
```

I think it's something related with the zip/7zip support, I've tried every `build_pack.py` all the way down to commit 8cf6c9c (Aug 14, the first one with zip support) and all of them returned this error, also tried with SMDBs for other systems (Allways the latest commit).

The latest working `build_pack.py` is from commit 02608d0

The unorganized folder is composed from my old sets with some minor adds, when I bought my Mega Everdrive X7 (Dec 2018) I reorganized and ran the script in the entire collection, and now prepping myself to the SD2SNES PRO I decided to run the scripts again and add some updates.

Tonight I'll proceed with a full format in my system (for another reason) but will take advantage of that and run the script with a fresh system and Python install.

**Comment by frederic-mahe** [comment]
@Slashbunny any idea on what could cause that issue? @DhinCardoso you confirm that your input folder does not contain any zipped files?

**Comment by Slashbunny** [comment]
The traceback says:

```
  File ".../build_pack.py", line 231, in get_hashes
    with zipfile.ZipFile(filename, 'r') as z:
```

However, if it made it to that line, that means this check on the previous line succeeded:

```
    if zipfile.is_zipfile(filename):
```

Python's zip module appears to think `filename` is a zip file, but then fails to read it. There must be something strange about the file it's failing to read it at all. The module should return exceptions if there was something wrong with the file:

https://docs.python.org/3.3/library/zipfile.html

`OSError**: [Errno 22] Invalid argument` implies that the path to the file is invalid. It must be something about the name/encoding of the file or path. It still doesn't make sense that `is_zipfile()` can open and check the file (it reads the header of the file), but the `ZipFile` constructor thinks the path doesn't exist.

**Comment by st4rl3ss** [comment]
I confirm having the same issues in both Windows and Linux. I will try to find a solution during the weekend.

**Comment by DhinCardoso** [comment]
> @DhinCardoso you confirm that your input folder does not contain any zipped files?

I'm planning on adding some individually zipped files for test-purpose only, but so far all tests was on zip-free folders.

> There must be something strange about the file it's failing to read it at all.

Initially I suspected if the problem was some (or just one) files from my set. But the successful build using another version and the error persisting with other SMDBs (Tried Mega n N8 too) with the same behavior (the error pops out close to the build end, 90%ish) made me change my mind

**Comment by frederic-mahe** [comment]
@DhinCardoso the latest `build_pack.py` fixed by @bodgit should fix issues with zipped files.

**Comment by frederic-mahe** [comment]
OK, I've tested thousands of input files with `build_pack.py` and I've find a few non-zipped files that `zipfile.is_zipfile()` mistakens for zipped files because they contain a magic number typical of zip archives.

An example of such a file is `Hiouden - Mamono-tachi to no Chikai [Motoi Sakuraba & Shinji Tamura-Emancipation].spc` (MD5: `da85205c66838843dafd5bd7b1322723`). It is a Super Famicom music ROM (it plays in the music player Audacious). Using it as input file for `build_pack.py` immediately triggers the error reported above, with the same traceback. In that case the magic number is `stringEndArchive = b"PK\005\006"` (see [zipfile.py code](https://github.com/python/cpython/blob/master/Lib/zipfile.py)), occurring far inside the file.

`build_pack.py` could be modified:
- to check also for file extension (`.zip`),
- or to use also a `file type` test? (on my computer, the command `file` does not mistaken the file above for a zip file)

These solutions are not very robust or portable. What do you think @Slashbunny @bodgit ?

**Comment by bodgit** [comment]
I would say checking that the file ends in `.zip` is probably sufficient.

**Comment by Slashbunny** [comment]
Wrapping it in a `try:`, catching the exception, and simply continuing the process in these scenarios would be the most robust solution. As I understand it, this is the "python way" (I am not a python programmer):

https://docs.python.org/3/glossary.html?highlight=eafp#term-eafp

In other words, philosophically, it's better to `try/catch` than `if/else`. 

Practically speaking, just checking `.zip` is probably sufficient as @bodgit said. 👍

**Comment by frederic-mahe** [comment]
Thanks you both for your input. I've decided to go for a `try/catch` structure, to silently pass on OS errors. The assumption is that if there is a genuine issue with a file, it will trigger an error during the first hash pass.

@DhinCardoso that new version of the `build_pack.py` script works has expected. Please give it a try.

**Comment by DhinCardoso** [comment]
**First and most important:** You guys are such awesome humans... I wish the planet could breed more of your kind! @frederic-mahe @Slashbunny @bodgit @SmokeMonsterPacks and many many others who anonymously contribute for a better world bit by bit. 

**Second:** I'm unable to do the test right now, tomorrow morning I will update this thread with news. Thanks

**Comment by frederic-mahe** [comment]
@DhinCardoso did you have the opportunity to test the new version of the script?

**Comment by DhinCardoso** [comment]
Sorry for the absurd delay to answer, but I'm glad to announce everything ran smoooooooth ♥ on every test (GBA, GBC, Master System, Megadrive, N64 and finally Snes

```
C:\Users\dhinc>"C:\Program Files (x86)\Python38-32\python.exe" "C:\Users\dhinc\Desktop\EverDrive-Packs-Lists-Database-master\build_pack.py" -i "C:\Users\dhinc\Desktop\SD2SNES" -d "C:\Users\dhinc\Desktop\EverDrive-Packs-Lists-Database-master\EverDrive Pack SMDBs\Super EverDrive & SD2SNES SMDB.txt" -o "C:\Users\dhinc\Desktop\OUTPUT" -m "C:\Users\dhinc\Desktop\SD2SNES.txt"
processing file:     44259
coverage: 13054/13114 (99.54%)
```
