### ISSUE TITLE
MiSTer switch to new MRA structure for arcade

### ISSUE THREAD

**Issue by sigboe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#132]
MiSTer has added support for a new way of handling Arcade roms. 

```
.
└── _Arcade
    ├── Game_Shortcut.mra
    ├── cores
    │   └── Arcade_core.rbf
    ├── hbmame
    │   └── hbmame_rom.zip
    └── mame
        └── mame_rom.zip

```

Some cores are deprecated and switched to only being MRA shortcuts for roms to another compatible core. So I hope this is switched over so that the SmokeMonsterPack is compatible with the newest versions of the cores.

**Comment by frederic-mahe** [comment]
Noted, thanks @sigboe
