### ISSUE TITLE
Info for flashcarts

### ISSUE THREAD

**Issue by actraiser30** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#134]
Hello there great scripts you have

i was wondering if you can provide any info about with what flashcarts are this packs in your script compartible ?

Atari 2600/Atari 5200/Atari 7800/Colecovision/Vectrex/AtariLynx

i mean for example there are 3-4 flash carts for atari2600 which one is working with your pack of atari2600?

thank you

**Comment by frederic-mahe** [comment]
@actraiser30 if you still out there, packs are no longer aiming for a specific flashcart, but rather for a full set of what can run on real hardware, with special folders for ROMs that are unsupported by a specific flashcarts.

**Comment by NayoMays** [comment]
Hey @actraiser30 just wanted comment and say the Harmony Encore cartridge works great with this script! Recommended you copy over to your SD/microSD card using Windows, and not the script though (will be out of order otherwise).

**Comment by frederic-mahe** [comment]
Thanks for your feedback @NayoMays !
