### ISSUE TITLE
Super EverDrive & SD2SNES SMDB.txt: Remove SA-1 Speed Test (PD) v3.2 Vitor Vilela.sfc

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#139]
Newer version exists in pack here:
`3 Special Chip Games/SA-1/Demos & Tools/SA-1 Speed Test (PD) v5.1 Vitor Vilela.sfc`
Remove the following:
`5 Tools & Service Test Carts/SA-1 Speed Test (PD) v3.2 Vitor Vilela.sfc`

**Comment by frederic-mahe** [comment]
thanks, fixed in https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/ac5ffe03925a4829f1ce2c7aa7a6b1e8caf69cef
