### ISSUE TITLE
Super EverDrive & SD2SNES SMDB.txt

### ISSUE THREAD

**Issue by kraqh3d** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#14]
Is there a reason why these two srm save files exist in the database?  Or are they unnecessary and should be omitted?

> d0ff1b294b5288d1ae1421eadf5b2d38a8752b76d472ff30bed9028e25b1c5b8	SD2SNES/3 BS-X Satellaview/BS Dezaemon (J).srm
> 51a9a0c95289bd90e5fc8139294225af4e10933f95e00b4bfe7625095a5f383b	SD2SNES/4 Hacks/Selections/SMW Super Mario Logic (SMW Hack) Final Theory 2017-10-21.srm

(I found them while working on the audit script.)

**Comment by frederic-mahe** [comment]
Good catch @kraqh3d 

I've pushed a new version of `parse_pack.py` excluding all files ending with `.srm`. There are only three files in all the packs:
```
MSU-1/New MSU-1/Flashback - The Quest for Identity MSU (USA) v2 LuigiBlood, Conn Fix/FB_MSU1.srm
Super EverDrive & SD2SNES SD2SNES/3 BS-X Satellaview/BS Dezaemon (J).srm
Super EverDrive & SD2SNES SD2SNES/4 Hacks/Selections/SMW Super Mario Logic (SMW Hack) Final Theory 2017-10-21.srm
```

**Comment by SmokeMonsterPacks** [comment]
Those are there by mistake. Thanks for the updated script!
