### ISSUE TITLE
Super EverDrive & SD2SNES SMDB.txt: RPG Tsukuru - Super Dante (Japan).bs / Jewel of Live II (Japan).bs

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#141]
I think the following entry is misnamed:
`3b6cd63d813d94fa9832c146959bd00c17d2707c25686546815e769096e15084	SD2SNES/3 BS-X Satellaview & Sufami Turbo/BS-X Unpatched - SD2SNES-Only/RPG Tsukuru - Super Dante (Japan).bs	a134ffd765db8f357bd48de871adf0c579730b83	d3cfe6545f8c27e293ba42bbe2217eb5	b2550afb`

I believe it should be named "Jewel of Live II (Japan).bs" as defined by its [entry](https://datomatic.no-intro.org/?page=show_record&s=77&n=3634) in nointro and based on info from the [dumper](https://twitter.com/notrevenant/status/1109219470864732161)

**Comment by frederic-mahe** [comment]
thanks, fixed in https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/715147b338d7af8b76db1fa68edc8350b44fffa6
