### ISSUE TITLE
Super Everdrive & SD2SNES SMDB has a special character causing an error

### ISSUE THREAD

**Issue by dukesilverfan** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#146]
I was experiencing a build error with the SNES romset SMDB.txt, but I was able to find it, delete it, and now it builds fine. I am on a Mac, so it may be on my end, but I figured I would share.

On line 13,577, there is a Ò in the filename of:
SD2SNES/4 SPC Audio/2 Misc SPC/battle of the bits spcs/BotB 14983 AugustusBlkheart - L+Òngholmen.spc

**Comment by frederic-mahe** [comment]
fixed
