### ISSUE TITLE
error running script

### ISSUE THREAD

**Issue by iceman1981** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#148]
following the readme.md, i am unsure what i am doing wrong.

I renamed the directories and smdb.txt to make it easier.

I have the "no intro" SNES romset. 3400 or so roms

`ant@ant-lenovo:~/Downloads/smoke$ sudo python3 build_pack.py -i "/home/ant/snes_roms" -d "/home/ant/Downloads/smoke/smdb/snes.txt" -o "/home/ant/everdrive/" -m "/home/ant/missing.txt"
Traceback (most recent call last):
  File "build_pack.py", line 259, in <module>
    DATABASE, NUMBER_OF_ENTRIES = parse_database(TARGET_DATABASE)
  File "build_pack.py", line 142, in parse_database
    for line in target_database:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 1797: invalid continuation byte
`

**Comment by tjanas** [comment]
That byte 0xf1 is a non-ascii byte that is in your snes smdb text file.
It is probably because of [this](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/issues/146) issue.

Check line 13577 of your snes.txt file and remove the special character:
`SD2SNES/4 SPC Audio/2 Misc SPC/battle of the bits spcs/BotB 14983 AugustusBlkheart - L+ñngholmen.spc`

**Comment by iceman1981** [comment]
Thank you!

**Comment by alexeyza** [comment]
I encountered this issue as well some time ago, and submitted a pull-request to fix it.
https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/142

**Comment by frederic-mahe** [comment]
thanks @iceman1981 @tjanas and @alexeyza  I am very sorry for the time it took me to fix this (see https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/f78b7b144555868091a1d4e90d8b718cf41bf678).
