### ISSUE TITLE
GBA bad dump: Super Puzzle Fighter II

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#171]
Existing entry in GBA SMDB:

`9f7f7ee2245051ed4f22ff82b84776a06b5fd4b1a0574acb974b7b1f754a6d2d	EverDrive GBA/1 USA - P-S/Super Puzzle Fighter II Turbo (USA).gba	801df7f69fc574a17e8c5efce6ca18ae5749aa97	14d0771c15676e2b3b75c4c149879586	9cd25c7e`

This was [found to be a bad dump](https://datomatic.no-intro.org/index.php?page=show_record&s=23&n=0979). It has been redumped on 2020-02-10.

Also the filename is incorrect in the SMDB (it should be `Super Puzzle Fighter II (USA).gba`).

**Comment by frederic-mahe** [comment]
fixed in c8eb95405c604a20ef84d4c199cf78e0ad980cae
