### ISSUE TITLE
MD ED: Lethal-wedding.md

### ISSUE THREAD

**Issue by maniac79** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#176]
Can anyone please confirm whether the Lethal-wedding.md hashes in the Mega EverDrive SMDB are from a demo version? I believe that's the case but can't confirm it.

However, I downloaded the demo today from the distributor's website (Mega Cat Studios) and the filename and hashes are different:
LW_build_0446.bin
6d372fe4
96689b555322cbcc1fd0b3615f449081
fe6533d013100daa65d26e26bbaae551422f57df

Maybe a later build?
Or are the hashes from SMDB from the full game?

**Comment by maniac79** [comment]
After what happened today:
Maybe Lethal-wedding.md should be removed as long as we can't verify which version it is?

**Comment by frederic-mahe** [comment]
Yes, remove the unidentified version, and add the publicly available demo version. Can you please make a pull request for that?

**Comment by maniac79** [comment]
Pull Request #180
