### ISSUE TITLE
Mega Everdrive pack cleaning

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#18]
Parsing the Mega Everdrive SMDB and excluding files ending with `32X or md or bin or gen or sms or sg or sc or gg`:
```sh
dos2unix < Mega\ EverDrive\ SMDB.txt | grep -vEi "(32X|md|bin|gen|sms|sg|sc|gg)$"
```
returns a long list of files source and compilation files, all in:
```
Mega EverDrive/4 Homebrew/Demos & Intros/Extended SSF Dev Demo Sample - Krikzz/src/
Mega EverDrive/5 Tools & Service Test Carts/Extended SSF Dev Demo Sample - Krikzz/src/
```
Should `/Extended SSF Dev Demo Sample - Krikzz/src/` be excluded by the `parse_pack.py` script?

**Comment by SmokeMonsterPacks** [comment]
Yes, those can be excluded. Thanks!

**Comment by frederic-mahe** [comment]
Done
