### ISSUE TITLE
NES and Famicom extensions (N8 SMDB)

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#189]
@tjanas you might want to have a look at this one. If we accept entries with extensions `.nes`, `.fds`, `.nsf`, and `.qd`:
```sh
dos2unix < EverDrive\ N8\ \&\ PowerPak\ SMDB.txt | cut -f 2 | grep -ivE "\.(nes|fds|nsf|qd)$"
```
What should we do with the following files? Are `.wav` files legit?
```
EverDrive N8/3 NSF Music for PowerPak/NSF/F/Family Trainer - Aerobics Studio Sample 1.wav
EverDrive N8/3 NSF Music for PowerPak/NSF/F/Family Trainer - Aerobics Studio Sample 2.wav
EverDrive N8/3 NSF Music for PowerPak/NSF/F/Family Trainer - Aerobics Studio Sample 3.wav
EverDrive N8/3 NSF Music for PowerPak/NSF/F/Family Trainer - Aerobics Studio Sample 4.wav
EverDrive N8/3 NSF Music for PowerPak/NSF/F/Family Trainer - Aerobics Studio Sample 5.wav
EverDrive N8/3 NSF Music for PowerPak/NSF/F/Family Trainer - Aerobics Studio Sample 6.wav
EverDrive N8/3 NSF Music for PowerPak/NSF/F/Family Trainer - Aerobics Studio Sample 7.wav
EverDrive N8/3 NSF Music for PowerPak/NSF/F/Family Trainer - Aerobics Studio Sample 8.wav
EverDrive N8/Unsupported/N8 - Too Large/45-in-1 (JY-120A) (Unl) [U][!].unf
```
Maybe the `.unf` extension can be replaced with a `.nes`?

**Comment by tjanas** [comment]
Assuming they are actual wav files, they should be removed/replaced. NSF format is described [here](https://wiki.nesdev.com/w/index.php/NSF).

Should we add the raw .qd files to an FDS pack even though they aren’t directly playable by Everdrive/PowerPak/emulator/FDSStick?

**Comment by tjanas** [comment]
Also, for reference, [here is the utility I made to convert QD to FDS](https://gist.github.com/tjanas/74e5e21ceee4507c9fbdd03bfdb2e1b8).

**Comment by frederic-mahe** [comment]
> Also, for reference, here is the utility I made to convert QD to FDS.

Nice!

Regarding `.qd` files, here is the list of entries in N8:
```
EverDrive N8/3 Famicom Disk System/4 FDS Betas, Prototypes, Revisions/FDS Revisions/Clu Clu Land (Japan) (GameCube Edition).qd
EverDrive N8/3 Famicom Disk System/4 FDS Betas, Prototypes, Revisions/FDS Revisions/Link no Bouken - The Legend of Zelda 2 (Japan) (Collector's Edition).qd
EverDrive N8/3 Famicom Disk System/4 FDS Betas, Prototypes, Revisions/FDS Revisions/Nazo no Murasamejou (Japan) (GameCube Edition).qd
EverDrive N8/3 Famicom Disk System/4 FDS Betas, Prototypes, Revisions/FDS Revisions/Super Mario Brothers 2 (Japan) (DV 0) (GameCube Edition).qd
EverDrive N8/3 Famicom Disk System/4 FDS Betas, Prototypes, Revisions/FDS Revisions/Zelda no Densetsu - The Hyrule Fantasy (Japan) (Collector's Edition).qd
EverDrive N8/3 Famicom Disk System/4 FDS Betas, Prototypes, Revisions/FDS Revisions/Zelda no Densetsu - The Hyrule Fantasy (Japan) (GameCube Edition).qd
```
I assumed these entries were playable on an Everdrive. Is that not the case? If not, then I think they should not be here, as they could not originally run on real hardware, and were not modified to run on real hardware through cartridge emulators.

**Comment by frederic-mahe** [comment]
partially fixed in 49061668147f046789610172c4334881b577ba5f

Now we need to decide what to do with the `.qd` entries.

**Comment by tjanas** [comment]
In the FDS pack I am making, I was thinking about creating a top-level directory called QD that could contain them as source material, similar to how we keep other non-playable files like BIOSes. Especially since it is used for derived QD2FDS data.

On the topic of derived data, is there any value in storing actual IPS and BPS files in the repo that are used to create patches/hacks present in the SMDB? I don’t think anyone is archiving them properly. Although it becomes a large task.

**Comment by frederic-mahe** [comment]
> In the FDS pack I am making, I was thinking about creating a top-level directory called QD that could contain them as source material, similar to how we keep other non-playable files like BIOSes. Especially since it is used for derived QD2FDS data.

I am not sure. Maybe you could add a `QuickDisk originals` directory as a sub-directory of the QD2FDS? the name of the directory should indicate what these entries are and the fact that they are not playable on FDS to avoid confusion.

> On the topic of derived data, is there any value in storing actual IPS and BPS files in the repo that are used to create patches/hacks present in the SMDB? I don’t think anyone is archiving them properly. Although it becomes a large task.

That's a huge endeavor. If you have the patched rom and the original, can you recreate these files automatically? To link a patched rom and its patch, you could give them the same name, but some entries are the product of several independent patches, how are you going to name the patch files?

**Comment by tjanas** [comment]
I like the subdirectory idea.

**Comment by tjanas** [comment]
In the meantime, what should we do with the few .qd files that made their way into this pack?

**Comment by frederic-mahe** [comment]
Can you move them to a subdirectory? That would make future changes easier. Or remove them. I don't have a strong opinion on that one.

**Comment by tjanas** [comment]
I’ll remove them for now. They will be added again as part of the FDS overhaul.
