### ISSUE TITLE
Gameboy Advance Video ROMs

### ISSUE THREAD

**Issue by cfillak** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#2]
Why are the GBA Video ROMs not included in the GBA Everdrive db?

**Comment by SmokeMonsterPacks** [comment]
Oh, I pulled those a long time ago to save space. They should be added back. I'll try to get them in the next update.

**Comment by frederic-mahe** [comment]
I suggest to keep the issue opened until the ROMs are included back.

**Comment by frederic-mahe** [comment]
There is only one file not ending with `gba` in the GBA SMDB:
```
ee1f05e0dde1ca1c3711cc7efddc40e13418b45edc213f70521284444ff87605        EverDrive GBA/4 Game Series Collections/Genre & Franchise/Puzzle/Sort By - General Puzzle/WarioWare - Twisted! (USA).gba copy
```
I assume it should be renamed.

**Comment by SmokeMonsterPacks** [comment]
Thanks, I'll get that fixed (Game Series Collections mistake). I think tjstogy must leave filename extensions hidden in his file manager or something. I'll contact him about this and see if I can prevent this in the future.

**Comment by SmokeMonsterPacks** [comment]
I also have the video files added back and they'll appear in the next update. I'll hold off on that until I go through the GBA pack a little better though.

**Comment by frederic-mahe** [comment]
Two files to rename in the GBA set:
```
EverDrive GBA/4 Game Series Collections/Genre/Puzzle/Sort By - General Puzzle/WarioWare - Twisted! (USA).gba copy                                                                                                                                                                                                                                                
EverDrive GBA/4 Game Series Collections/Multiplayer/All Multiplayer Games/Sound of Thunder, A (USA) (En,Fr,De,Es,It).gba copy
```

**Comment by SmokeMonsterPacks** [comment]
Thanks!

I just saw this
<https://www.ebay.com/sch/m.html?_odkw=&_ssn=retroinnovation&hash=item23747cccae%3Ag%3A9BkAAOSwmgJY57HR&item=152278191278&_osacat=0&_from=R40&_trksid=p2046732.m570.l1313.TR0.TRC0.H0.Xneo+geo+autofire.TRS5&_nkw=neo+geo+autofire&_sacat=0>
seller has controller adapters to Neo Geo/Jamma, which would be perfect for
the HAS. He makes SNES, Genesis, and Playstation. There are some
great/cheap Playstation sticks that would be perfect for arcade gaming :)

**Comment by frederic-mahe** [comment]
```sh
dos2unix < EverDrive\ GBA\ SMDB.txt | cut -f 1,2 | grep -ivE "gba$"
```
returns nothing. The GBA Video ROMs are now included. All clear!
