### ISSUE TITLE
Submitting potential candidates for addition

### ISSUE THREAD

**Issue by ddbehsnilian** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#20]
Is there any way to suggest new entries for the packs? In this instance I've found there's a another translation/localization of Akumajou Densetsu (Castlevania III), by ShadowOne333, that starts where the Vice one left off. It follows the US canon (correct names) and has a translated title screen. It also comes in two flavors, one of them including an alternate sprite for Alucard that's more in line with the one from Symphony of the Night. Here is the link for the ROMhacking page http://www.romhacking.net/hacks/1983/

**Comment by SmokeMonsterPacks** [comment]
I don't accept requests for patches unless the patched ROM is sent to me (I got bogged down with requests). If you can message me a link to the patched ROM though, I can get it added. Thanks!
