### ISSUE TITLE
N8: Rush Hour (Unl) in wrong subdirectory

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#210]
`EverDrive N8/2 Unlicensed - A-Z/1 Unlicensed S-Z/Rush Hour (Unl).nes`

**Comment by frederic-mahe** [comment]
It is still in the wrong subdirectory:
`EverDrive N8/2 Unlicensed - A-Z/1 Unlicensed S-Z/Rush Hour (Unl).nes`
It should be in:
`EverDrive N8/2 Unlicensed - A-Z/1 Unlicensed L-R/Rush Hour (Unl).nes`

**Comment by tjanas** [comment]
I will fix it.
