### ISSUE TITLE
Amazing Spider-Man vs. The Kingpin, The (USA) (First Release) in different folder from rest

### ISSUE THREAD

**Issue by dukrous** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#213]
In MegaSD SMDB.txt, _Amazing Spider-Man vs. The Kingpin, The (USA) (First Release)_ is filed under `Sega CD/MegaCD/4 Betas, Demos, Prototypes, Revisions, etc/Revisions` when the rest of the pack is using `Sega CD/MegaSD/4 Betas, Demos, Prototypes, Revisions, etc/Revisions`.

**Comment by frederic-mahe** [comment]
thanks @dukrous this is fixed in 700c5a56d35b2ececcb832d47b9d2526f1a0bdee
