### ISSUE TITLE
MiSTer Add On Pack: NEOGEO.zip in SMDB

### ISSUE THREAD

**Issue by dukrous** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#216]
In the MiSTer Add On Pack SMDB, the Games/NEOGEO folder contains a reference to a zip file with all the NEOGEO roms in it. Not sure if the SMDB should have just the zip or just the roms, but not both.

**Comment by frederic-mahe** [comment]
thanks, that big zip file should not be there. Fixed in 54114bd79bbd99985bde3926a05030f031cf379d
