### ISSUE TITLE
Mega SD: wrong hashes against verified Redump set

### ISSUE THREAD

**Issue by qcretro** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#217]
I am building the MegaSD pack from a complete DAT verified Redump set and there are many hash mismatch against the pack. My set has been verified using Redump's latest 2020-02-24 DAT using RomVault 3.1.2.

 I've tried to isolate only what is related to redump in my missing list you will find attached.

[megasd_missing_build_onlyredump.txt](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/files/4516705/megasd_missing_build_onlyredump.txt)

**Comment by tjanas** [comment]
@qcretro I did a sanity check against my own personal redump archive and found the following:
```
Name: After Armageddon Gaiden - Majuu Toushouden Eclipse (Japan) (Track 33).bin
Size: 11938752 bytes (11 MiB)
CRC32: 093A7BDD
CRC64: 100FD1AFD2E9D634
SHA256: 7223C09D51358BE6359BC1450549CEABC7ACF05B1107B526904A77FB3BC828B0
SHA1: A878813AF566CFA7453DA54956C84FE17C529442
BLAKE2sp: F7A9ADCB6E9E45E1812D01FB5D8AEEABD45CE23248D5DCFE0F86CBDEC2052F49
```
[Redump](http://redump.org/disc/39500/):
```
#  | Size     | CRC-32   | SHA-1
33 | 11938752 | 093a7bdd | a878813af566cfa7453da54956c84fe17c529442 
```

[SMDB](https://raw.githubusercontent.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/master/EverDrive%20Pack%20SMDBs/MegaSD%20SMDB.txt):
`7223c09d51358be6359bc1450549ceabc7acf05b1107b526904a77fb3bc828b0	Sega CD/MegaSD/2 Japan - A-Z/1 A-L/After Armageddon Gaiden - Majuu Toushouden Eclipse (Japan)/After Armageddon Gaiden - Majuu Toushouden Eclipse (Japan) (Track 33).bin	a878813af566cfa7453da54956c84fe17c529442	d3c0b3f1d27c1d1229511f1660a99531	093a7bdd`

I don't see a mismatch here.

**Comment by tjanas** [comment]
Your included file of missing/mismatches included:
`After Armageddon Gaiden - Majuu Toushouden Eclipse (Japan) (Track 33).bin	7223c09d51358be6359bc1450549ceabc7acf05b1107b526904a77fb3bc828b0`

**Comment by qcretro** [comment]
There is something strange happening indeed because the hashes you provide match the ones I am seeing in Romvault against the same file I am running the script against.

**Comment by tjanas** [comment]
OK, please close this issue.

**Comment by qcretro** [comment]
I was running the script on Windows 10 over the network to a samba share, maybe that is the cause of the issue. I'll close this for now.
