### ISSUE TITLE
Thoughts on using SHA-1 instead of SHA-256?

### ISSUE THREAD

**Issue by coughlanio** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#22]
I've recently started looking at enhancing the tooling for these packs, particularly around collecting and verifying integrity of the ROM data. Presently, most preservation groups use SHA-1, MD5 and CRC to generate their DAT files, whilst these packs are generated using SHA-256. 

Do you think it would be better to utilize SHA-1, so there's some commonality between these packs and those of other groups? It would make it easier to track down and obtain missing files, and make potential co-operation between groups easier.

Taking it one step further, but possibly a much larger change, would be to utilize the same DAT format used by other groups. This would mean that a lot of the existing tooling that works with those sets, should automatically work with the SmokeMonster packs.

https://github.com/SabreTools/SabreTools/wiki/DAT-File-Formats#logiqx-xml-format

**Comment by frederic-mahe** [comment]
Hi @coughlanio 

I am going to implement your suggestion to include more hash values. You are right, it will make it easier for ROM hunters and people who would like to interface with other preservation groups. I think I'll keep the sha256 as the identification key, and simply add new tab-separated columns to the SMDB files, like so:
```
sha256 ./path/to/ROM crc32 md5 sha1
```
What do you think of that?

Regarding your suggestion to use a DAT format: SmokeMonster is organizing ROMs that work on flash carts (it could be anything: official ROMs, hacks, homebrew, fan translations, music players, etc). This might not be totally in line with what other preservation groups are doing and the DAT formats they developed to do so. I am not sure how SmokeMonster's proposed ROM organization fits into that, so I'll stick with the table format for now.

**Comment by SmokeMonsterPacks** [comment]
Excellent work! I'm traveling for a few weeks, and I'll issue the updated SMDBs as soon as I'm home. Keep up the great coding and new ideas! :D

On January 22, 2018 2:49:51 PM GMT-02:00, "Frédéric Mahé" <notifications@github.com> wrote:
>Hi @coughlanio ,
>
>the latest
>[commit](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/7a051fe753f891b1a567417edbbbfff8f4ff1759)
>implements the additional columns with sha1, md5 and crc32 hash values.
>
>I ran a few tests using [TOSEC](https://www.tosecdev.org/) hash values
>for certain ROMs has reference, and the results are correct. Now,
>@SmokeMonsterPacks needs to recreate all the SMDB files :-)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/issues/22#issuecomment-359488788

-- 
Sent from my phone. Please excuse my brevity.

**Comment by frederic-mahe** [comment]
> I'm actually working on a couple of supplemental tools for these ROM packs. Are there any avenues of real-time discussion for the project, such as Slack or Discord?

That sounds interesting. Sadly, I can barely keep up with work nowadays and it would be difficult for me to add real-time discussions into the mix (and our different time zones would make it even more complicated). I'd prefer to stick with asynchronous channels for now (github issues for example). Sorry about that.
