### ISSUE TITLE
Mega EverDrive SMDB: bad dump for Aladdin (USA) (Final Cut)

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#220]
[no-intro](https://datomatic.no-intro.org/?page=show_record&s=32&n=2408):
File: | [Aladdin (USA) (Final Cut).md | Aladdin (USA) (Final Cut).md](url)
-- | -- | --
Aladdin (USA) (Final Cut).md
  | Size: | 2384052
  | CRC32: | DD66B3FA
  | MD5: | AAD85DBD002F68E59BEA74942011ECF1
  | SHA-1: | 7398BD6DC7AED3F1D819F70360593FE50491DAC

SMDB currently has the following:
0059555e2c193d85d9b1053dd69eef43441fce09
157daf1b678660030bd06abdb6a76699
05cbb78e

**Comment by dukrous** [comment]
Hi, team...Aladdin (US) (Final Cut).md is also used in Mega Sg Jailbreak SMDB.txt, it also needs to be updated.

**Comment by tjanas** [comment]
I noticed that earlier today, I’ll fix it. Working on Mega Everdrive pack now, eventually the Mega Sg pack should just include the former.

**Comment by tjanas** [comment]
@dukrous [this pull request](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/254) should take care of it
