### ISSUE TITLE
Bad SHA256 for Ys III - Oath in Felghana MD+/31-DancingOnTheRoad.wav in MegaSD

### ISSUE THREAD

**Issue by dukrous** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#231]
I checked the original source, which seems to be https://drive.google.com/a/dukworld.net/open?id=1D7f9qUrFFWHUGwUlVdQkuBrR9_nfIdEM and noticed that the SHA256 for 31-DancingOnTheRoad.wav is calculated as `a0ad4d22972c712d0de6f22637d30e9bd7c69eb62f64f8c2695ad6c745ab0c0f`. Just to be certain I redownloaded it and it showed up as different.

parse_pack on my files shows all the files are the same, except for track 31. It outputs this:

> a0ad4d22972c712d0de6f22637d30e9bd7c69eb62f64f8c2695ad6c745ab0c0f	Sega CD/MegaSD/3 MegaSD MD+/Ys III - Oath in Felghana MD+/31-DancingOnTheRoad.wav	706bb13a0af7ce6794685b2f195e4af503e2bfa5	0e1cfbfb89aef7886db00da88f4b98b6	6f7ae784

**Comment by dukrous** [comment]
Also, if there's an easier way to report these than opening up issues let me know.

**Comment by tjanas** [comment]
I am unable to access your URL.
There is a link [here](https://www.zeldix.net/t1993-ys-iii-wanderers-from-ys) to the WAV and CUE pack by Game Sack, but that link appears to be dead.

**Comment by dukrous** [comment]
Try this link: https://twitter.com/gamesack/status/1173733463255502849

**Comment by tjanas** [comment]
I downloaded that zip file referenced there, and 
```
Name: 31-DancingOnTheRoad.wav
Size: 28757296 bytes (27 MiB)
CRC32: 6F7AE784
CRC64: BBB98DD6F0BD9300
SHA256: A0AD4D22972C712D0DE6F22637D30E9BD7C69EB62F64F8C2695AD6C745AB0C0F
SHA1: 706BB13A0AF7CE6794685B2F195E4AF503E2BFA5
BLAKE2sp: 52B8CD64370EC9DE79F73F2257117C245F9533E39A40E85BFF1E592D105FD93E
```

Here is the current SMDB entry:
`9d9ab224ce71249e3ff247c04f51785f5e7cb4a30c993a93822252d3993852ef	Sega CD/MegaSD/3 MegaSD MD+/Ys III - Oath in Felghana MD+/31-DancingOnTheRoad.wav	4883cd28271a35e4c16f369f4ba23743995c5943	379494b552e5f66700457afca3e53a3b	f537377e`

@dukrous you are correct, checksum does not match.

@maniac79 what was your source of these MD+ wav files?

**Comment by tjanas** [comment]
I created [this](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/234) pull request if @frederic-mahe @maniac79 @dukrous agree with this fix.

**Comment by maniac79** [comment]
> @maniac79 what was your source of these MD+ wav files?

https://archive.org/download/everdrivepack/MegaCD/MegaSD%20MD%2B/

**Comment by maniac79** [comment]
@tjanas I re-downloaded both sources and can confirm track 31 is the only different file. That's odd.

The .wav here is 1:10 long:
https://archive.org/download/everdrivepack/MegaCD/MegaSD%20MD%2B/

This .wav here is 2:43 long:
 https://drive.google.com/a/dukworld.net/open?id=1D7f9qUrFFWHUGwUlVdQkuBrR9_nfIdEM

Very odd. 1:10 seems a bit short but it seems to fade out correctly.
I also tend to believe that the 2:43 version is the correct one.
