### ISSUE TITLE
NES: add Gimmick! (Japan) (Memorial Series - Sunsoft Vol. 6) to Revisions

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#233]
[Gimmick! (Japan) (Memorial Series - Sunsoft Vol. 6).nes](https://datomatic.no-intro.org/?page=show_record&s=45&n=2827) is an NES rom extracted from an official PS1 disc. It should be represented in the Revisions directory, like NES roms extracted from GameCube discs.

**Comment by maniac79** [comment]
Only as a reminder:
When Pull Request #235 will be merged into main, this will be fixed.

**Comment by tjanas** [comment]
Per no-intro:
```
2020-05-28 08:14:09 Hiccup DELETED ARCHIVE
Gimmick! (Japan) (Memorial Series - Sunsoft Vol. 6)
comment: not sure i dumped this properly
```
