### ISSUE TITLE
NES: add the new game Steins;Gate release on Nintendo Switch?

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#236]
If _Steins;Gate_  is playable on real hardware, and if we want to list it in our database, then where should it go? Into a new top-level folder? `3 Nintendo Switch/Steins;Gate (USA) (Nintendo Switch).nes`

**Comment by tjanas** [comment]
My vote is unlicensed, since it is a brand new game and was obviously never licensed by Nintendo during the lifespan of the NES.

**Comment by tjstogy** [comment]
Agreed with tjanas, it doesn't belong in A-Z. Not sure where it belongs, but only games released during a consoles lifespan belong in there IMO.

**Comment by frederic-mahe** [comment]
@tjanas I think your recent work on the NES pack solves that issue:
`EverDrive N8/1 US - R-Z/Steins;Gate (USA) (Nintendo Switch).nes`
