### ISSUE TITLE
Any plans to do a PSIO pack?

### ISSUE THREAD

**Issue by FiZiX** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#24]
Are there any plans to make a ROM (in this case ISO) pack for the PSIO?

**Comment by frederic-mahe** [comment]
In France, a trilogy of books called _Playstation Antology_ was published two years ago. Its roughly 1,200 pages long and it documents the history of the Playstation with a year-per-year list of games: 4,150 games are described (more than 5,900 when including local versions).

A complete list of PSONE ISOs would be great, but storing the ISOs will certainly be a challenge, at least for now.

**Comment by FiZiX** [comment]
@frederic-mahe That's a good point. I know one fairly complete (North America only) PS1 ISO collection is about 500GB compressed. I have no idea what that would be uncompressed but it would certainly exceed 512GB, which is the largest size SD card currently available (and it's very expensive). I guess the options would be to either span the romset across multiple SD cards or leverage the ability of the PSIO to stream games over USB from a PC.

**Comment by benclaff** [comment]
Hi,
The ReDump dats are probably one of the most accurate and complete list of PS1 dumps out there. 
Right now, the most complete archives are ~1Tb for Europe, ~1Tb for Asia, and 0,5 Gb for US.
Currently these values are compatible only with hardrive-based solutions...

**Comment by frederic-mahe** [comment]
The first 32 GB SDXC card was introduced in March 6, 2009. The first 400 GB microSDXC card was introduced in In August 2017. That's a ten-fold increase in capacity in less than ten years. If that trend continues, we might be able to buy 2 TB (micro)SDXC cards in a few years.

The SDXC format is limited to 2 TB though, so it will not be possible to put the complete PS1 ISO collection on a card of that format, which is the one supported by the PSIO.

In the meantime, it would be great to pass on the word that now would be a great time to complete the inventory of PSONE games, ideally with attached hash values. I'd be happy if a PSONE pack existed but I am not the one who's going to build it :-)

**Comment by SmokeMonsterPacks** [comment]
Arithmaldor was actually working on an PS-IO Pack, and I have a PS-IO on order, so it would definitely be awesome to have a List ready. I haven't heard much from him about it though, but I assume that it is progressing slowly but surely. It's a huge research project for sure. We were even in talks with programmers from the PSIO forum who had scripts to auto-generate thumbnails. It will be cool if it happens, but don't expect it in the near future by any means :D

**Comment by frederic-mahe** [comment]
In that [forum post](http://atariage.com/forums/topic/242970-fpga-based-videogame-system/page-200#entry3918294), it is reported that the [redump](http://redump.org/) project estimates the PS1 set to represent 3.6 TB:
```
PS1: 3.605 TB (8204 dumps, avg. 0.45 GB per disc)
```
Sizes for other sets are also reported:
```
Dreamcast: 0.614 TB (564 dumps, avg. 1.11 GB per disc)
GameCube: 2.318 TB (1746 dumps, avg. 1.36 GB per disc)
PS2: 16.046 TB (6844 dumps, avg. 2.40 GB per disc)
PS3: 14.889 TB (1618 dumps, avg. 9.42 GB per disc)
PSP: 1.325 TB (1586 dumps, avg. 0.86 GB per disc)
Saturn: 0.642 TB (1554 dumps, avg. 0.42 GB per disc)
Wii: 4.460 TB (1031 dumps, avg. 4.43 GB per disc)
Xbox: 11.274 TB (1585 dumps, avg. 7.28 GB per disc)
Xbox 360: 4.685 TB (658 dumps, avg. 7.29 GB per disc)
```

**Comment by coughlanio** [comment]
I wonder if being more granular with the packs is an option as we get into more CD-based console ODE solutions. Like Project Peacock, we could offer SMDBs like `PSIO Shmup Collection` or `PSIO RPG Collection` etc.

**Comment by frederic-mahe** [comment]
@coughlanio what do you mean with being more granular? Is your idea to provide **subsets** of game sets for a given console, instead of trying to provide the complete library? I think that's a good idea. Setting intermediate goals toward a complete library will make it easier. As some games can be hard to categorize, I would recommend to start with even simpler lists, like "PS1 top 10 RPGs according to X" and "PS1 30 hidden gems according to Y".

Ultimately though, for very large collections such as PS2 and Xbox, we need to move away from `FAT32` and use file systems supporting _hard-links_. With hard-links, a given file can appear at several places in the folder hierarchy, under different names, without duplication of the data. One can create many lists and game collections, without taking more storage space.

**Comment by frederic-mahe** [comment]
I'll go ahead and close that issue for now. Feel free to open it again when the PS-IOs will be widely distributed.

**Comment by frederic-mahe** [comment]
For future reference, the SD Association [announced](https://www.sdcard.org/press/SD_EXPRESS_A_REVOLUTIONARY_INNOVATION_FOR_SD_MEMORY_CARDS.pdf) that: 

> the maximum storage capacity in SD memory cards grows from 2TB with SDXC to 128 TB with the new SD Ultra Capacity (SDUC) card.

That should be enough to store all PS1 games.
