### ISSUE TITLE
Limited to everdrives ?

### ISSUE THREAD

**Issue by benclaff** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#25]
Hi,
I was just wondering if this project is focused only on everdrive devices or could move beyond for devices presenting the same limitations (basically, a limited number of roms per folder) ?
I'm particularly thinking about the Satiator, which will be a sdcard reader replacing the sega saturn laser block which is right now developped by this guy: https://www.patreon.com/prof_abrasive/posts

Best,

**Comment by frederic-mahe** [comment]
hi @benclaff 

I cannot speak on SmokeMonster's behalf, although I would say that the goal is to provide curated and organized packs of ROMs (or ISOs) that can work on real hardware (consoles, arcade PCBs), whatever is the mean to load these ROMs (Everdrives, flash carts, PSIO, Satiator, etc). After much work, packs are now available for most retro-consoles.

Now, building packs for CD-based consoles would certainly be great, but also very challenging (large and voluminous game libraries). And I don't know who's going to tackle this job.

**Comment by SmokeMonsterPacks** [comment]
The EverDrive nomenclature is basically a carry over from when I first started my work on packs. The project has now expanded to essentially encompass any real hardware flash solution, so flash carts of all kind are game, including the Satiator. It would definitely be a huge project to do a complete Saturn List, and it might take some tweaking to the parse pack, but it's definitely doable if someone is up to it. In the near future when we have inexpensive 1TB+ SD cards, packs like that will be in great demand.
