### ISSUE TITLE
Non UTF-8 characters in GBA & NT SMDBs.

### ISSUE THREAD

**Issue by coughlanio** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#26]
Currently working on my own tool which parses the SMDB format, and I'm running into the following error: 

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 2419: invalid start byte
```

These two files appear to be encoded in Windows 1252. We should try and keep all encoding to UTF-8

**Comment by coughlanio** [comment]
Sent PR #27 to fix this.

**Comment by SmokeMonsterPacks** [comment]
Thanks, coughlania. I went fixed the non-UTF-8 characters early on, but it looks like more found their way back. Could you please send me a list of the NT files that need changes and I'll fix them upstream. I corrected the GBA list just now.

**Comment by coughlanio** [comment]
@SmokeMonsterPacks you should be able to find them here: https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/27/files

**Comment by SmokeMonsterPacks** [comment]
Perfect, thank you!

**Comment by frederic-mahe** [comment]
That problem should be solved upstream (`parse_pach.py` can now detect non-ASCII characters).

**Comment by frederic-mahe** [comment]
I can confirm there are no non-ASCII characters in the SMDB files today:
```sh
grep -P -n "[\x80-\xFF]" *.txt
```
returns nothing.
