### ISSUE TITLE
Invalid MiSTer.txt unicode character continuation

### ISSUE THREAD

**Issue by pashdown** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#260]
I was getting the following output when trying to use the MiSTer SMDB:

`Traceback (most recent call last):
  File "EverDrive-Packs-Lists-Database/build_pack.py", line 271, in <module>
    DATABASE, NUMBER_OF_ENTRIES = parse_database(TARGET_DATABASE)
  File "EverDrive-Packs-Lists-Database/build_pack.py", line 146, in parse_database
    for line in target_database:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 623: invalid continuation byte`

I eventually found it was this causing the problem:
`Pelé's Soccer - Pelé's Championship Soccer`

I don't know why the unicode failed to decode in python.  Vim shows it properly, although viewing it with cat does not.  I changed the **é** to an **e** and it fixed the problem.

**Comment by frederic-mahe** [comment]
Thanks for reporting this, fixed in d218b7bed264171a056b2eacb8bf7ee799b307e4
