### ISSUE TITLE
SNES/NES Mini Classic Support

### ISSUE THREAD

**Issue by actraiser30** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#264]
Hi, is it possible to add support for SNES/NES Mini Classic Consoles with all the systems/consoles supported by Hakchi ??

thanks

**Comment by tjanas** [comment]
No. How would that work exactly? I think that is beyond the scope of the EverDrive packs. There are multiple methods on how games could run via Hakchi, such as using the native Canoe emulator, or using one of many retroarch cores. Each have different levels of compatibility, performance, and configuration tweaks required.

**Comment by actraiser30** [comment]
ok no problem,is it easy to add in the SNES Pack in the NES-to-SNES Hacks Castlevania for nes ??

thanks

**Comment by tjanas** [comment]
Can you provide a link to the hack details?

**Comment by actraiser30** [comment]
I mean to make the nes castevania game converted to smc format line the
ones the folder nes to snes hacks folder in the packs had. What link you
want ?


Στις Πέμ, 7 Μαΐ 2020, 17:43 ο χρήστης Terry Janas <notifications@github.com>
έγραψε:

**Comment by tjanas** [comment]
If there is a rom hack, please provide the link to the hack on romhacking.net, zophar.net, etc that provides the source rom details (e.g. checksum), the IPS/BPS patch, etc

**Comment by actraiser30** [comment]
Sorry but understand wrong i though you put the others roms in the pack if
i could find it i wouldn't ask you to put it in the pack.do you happen to
know who did the conversions for the nes to snes hacks ? Or what tool its
used to do so?

Στις Πέμ, 7 Μαΐ 2020, 18:12 ο χρήστης Terry Janas <notifications@github.com>
έγραψε:

**Comment by frederic-mahe** [comment]
hi @actraiser30 if there is a list of ROM hacks you would like to see included in the the SNES's SmokeMonster database, please send us links. In the meantime, I am going to close that issue.
