### ISSUE TITLE
Submitting SMDBs

### ISSUE THREAD

**Issue by iCach0** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#29]
Hi, is submitting small collection SMDBs encouraged? I've just made a couple of small ones for SNES, one for the Game Sack SNES episode and the other for Cinemassacre's Top 10 Obscure SNES Gems. I'm attaching them here but please let me know if there's an appropriate procedure for submitting these.
[The Super Nintendo - Game Sack (YouTube) SMDB.txt](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/files/1741234/The.Super.Nintendo.-.Game.Sack.YouTube.SMDB.txt)
[Top 10 Obscure SNES Gems - Cinemassacre (YouTube) SMDB.txt](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/files/1741235/Top.10.Obscure.SNES.Gems.-.Cinemassacre.YouTube.SMDB.txt)

**Comment by frederic-mahe** [comment]
thanks @iCach0 that could be a nice addition to the Super Nintendo's `Game Series Collections` folder. We'll see if @SmokeMonsterPacks includes it when he'll be back from his holidays.

**Comment by SmokeMonsterPacks** [comment]
Thank you @iCach0. I'll get these wrapped into the next GSC update :D
