### ISSUE TITLE
PC Engine: entries found ONLY in Game Series Collections 

### ISSUE THREAD

**Issue by Ryan-Myers** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#299]
Game Series Collections should always be a subset of entries found elsewhere. It should not be required to have Game Series Collections to produce 100% coverage of an SMDB.

This is essentially a continuation of the idea in #237. Only two games this time.

Below are those that are only found in GSC:
```
036 Son Son II (J) T+Eng v1 someitalian123.pce	d79e292fab50736f7371b9b8b625b5f8c15f098dffeed2b6e87d3b617a30b1b8
R-Type II (Tai Sang Version) (J).pce	9e876a444f8dbf654ed7f42f54c763211299c2df7985e5b6c88aaf49a6b98f5e
```

**Comment by tjanas** [comment]
I will work on this.

**Comment by tjanas** [comment]
I patched the no-intro dump of Son Son II, the patched rom has the following checksum:
```
Name: Son Son II English.pce
Size: 262144 bytes (256 KiB)
CRC32: 1A0599B4
SHA256: F2F5EA7514F15FD75283E708FD32BA0964488B0916ABEF28AFB46DA6DA21F3A3
SHA1: 3A53ED2FF692E277C55FA287B1D8281A50B0DF3E
```
This one is bad (the other instances of this translation-patched rom are good):
`Turbo EverDrive/4 Game Series Collections/Best-Of Lists/Top 100 List - Retro-Sanctuary.com/036 Son Son II (J) T+Eng v1 someitalian123.pce`
