### ISSUE TITLE
N64 Zelda no Densetsu - Toki no Ocarina possible bad dump

### ISSUE THREAD

**Issue by cfillak** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#3]
According to the N64 DB, the ROM "Zelda no Densetsu - Toki no Ocarina - Zelda Collection Version (J) (GC) [!].z64" has a SHA256 value: da91bd0f0a4e8382838a4eac455ed09f7236d951423e8039dd308bc73be8b090.

There is no ROM with this title in the N64 No-Intro set (neither normal nor byte-swapped).
There is a non byte-swapped version of this ROM called "Zelda no Densetsu - Toki no Ocarina GC (Japan) (GameCube Edition).z64" with SHA256 value:
c1b83e01bb2effc40cca233acf47a126d4eac974523184cbdc2fd0b18b0ac0bf

The byte-swapped version is called "Zelda no Densetsu - Toki no Ocarina GC (Japan) (GameCube Edition).n64" with SHA256 value:
f213d482b7b2c196ff6d57a1c5bffe9105f50147d12ce81fa22cc1677a28a0d8

I think either of these may be what this ROM is supposed to be.

**Comment by frederic-mahe** [comment]
Hi @cfillak,

The `2 Japan - A-Z` add-on pack mirrored on archive.org contains the following ROMs:
```
d5b3bc6ce43e567ff879b6f004eaf54372d1bab8e88b6121ef3b74ba765b1006  Zelda no Densetsu - Toki no Ocarina GC Ura (Japan) (GameCube Edition).z64
c8cbace47ae4d2bc36d75716d260c81956d7380b4812282f88b2a0b40e8e3e1d  Zelda no Densetsu - Toki no Ocarina (Japan) (Rev B).z64
```
Names and hash values correspond to the names and hash values in `EverDrive 64 & 64drive SMDB.txt`.

The mirrored pack does not contain the `Zelda no Densetsu - Toki no Ocarina - Zelda Collection Version (J) (GC) [!].z64` ROM you are referring to. That ROM might come from another ROM set. @SmokeMonsterPacks can you confirm?

**Comment by ddbehsnilian** [comment]
Hi, I'm having the same issue as @cfillak. Line 749 of the N64 SMDB file refers to EverDrive 64/2 Japan - A-Z/Zelda no Densetsu - Toki no Ocarina - Zelda Collection Version (J) (GC) [!].z64 and has a checksum value of  da91bd0f0a4e8382838a4eac455ed09f7236d951423e8039dd308bc73be8b090.
This file isn't present (or at least I couldn't find it) in the archive.org packs I downloaded yesterday. Unpacked the main pack, the Europe and Japan add-ons as well as the collections add-on to a new folder, run the scripts and the generated missing file lists only the mentioned Zelda ROM. (processing file: 3066, coverage is 99.96%). The closest I could find is a file with the name "Zelda no Densetsu - Toki no Ocarina GC Ura (Japan) (GameCube Edition).z64" and checksum d5b3bc6ce43e567ff879b6f004eaf54372d1bab8e88b6121ef3b74ba765b1006 which is listed in the SMDB (line 750) as "EverDrive 64/2 Japan - A-Z/Zelda no Densetsu - Toki no Ocarina GC Ura (Japan) (GameCube Edition).z64"

**Comment by frederic-mahe** [comment]
It seems that this particular rom is in the GoodN64 set, but I cannot find a copy of that set to confirm that.

**Comment by kraqh3d** [comment]
I can confirm that this rom exists in the GoodN64 set.  Below is a sha256sum from the v3.14 set.

`sha256sum *Densetsu*GC*`
>c1b83e01bb2effc40cca233acf47a126d4eac974523184cbdc2fd0b18b0ac0bf  Zelda no Densetsu - Toki no Ocarina GC (J) (GC) [!].z64
>4ee156612f4a5c50e4966dd69798952342b081d60b1fb494cac6b0eafe39456e  Zelda no Densetsu - Toki no Ocarina GC URA (J) (GC) [!].z64
>*da91bd0f0a4e8382838a4eac455ed09f7236d951423e8039dd308bc73be8b090  Zelda no Densetsu - Toki no Ocarina - Zelda Collection Version (J) (GC) [!].z64*

**Comment by frederic-mahe** [comment]
I've created a wiki entry for [hard to find ROMs](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/wiki/Hard-to-find-ROMs-for-pack-builders). I am not sure how that wiki page will evolve though: maybe pack builders will have to create their own website with thousands of links pointing to ROMs scattered throughout the internet?

**Comment by SmokeMonsterPacks** [comment]
That is definitely a GoodN64 ROM and doesn't belong, so I'll pull it. Sorry for the confusion on this!

**Comment by frederic-mahe** [comment]
Hi @SmokeMonsterPacks , no problem, I've deleted the wiki entry.
