### ISSUE TITLE
MSU1 Missing information

### ISSUE THREAD

**Issue by iCach0** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#30]
Hi, I've been spending some time building the MSU1 pack with the latest SMDB and scripts. The main issue I have is that the missing file list that is generated by the build script only lists filenames (no hashes). There are several cases of games that have more than 1 MSU1 patch/PCM set, so if you're missing one of those files, there's no way of knowing which one you're missing from the missing file list. My workaround so far has consisted of looking inside the folders after the build pack has finished to see what's missing. It would be really helpful if the generated missing file list also listed the hashes for missing files. Also, there are also a lot of miscellaneous files in the MSU1 SMDB that don't seem to belong there, like .xdelta patches, instruction files (pdf, docx, txt, rtf, etc), emulator support files like manifest.bml.

**Comment by frederic-mahe** [comment]
thanks for the suggestion @iCach0 

I've pushed a new version of `build_pack.py` that now reports the hash values of the missing files (commit 3e61ab3818f9cb235e22e4b1b532b63636999713). Let me know if that works for you.

**Comment by frederic-mahe** [comment]
Regarding the MSU1 pack, I've opened a separate issue (#31).

**Comment by iCach0** [comment]
Works beautifully! Thank you very much!
