### ISSUE TITLE
NES: Final Fantasy I & III Chaos Rush translations missing, II Chaos Rush translation outdated

### ISSUE THREAD

**Issue by Hydra-Spectre** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#309]

**Comment by tjanas** [comment]
> _No description provided._

Link to the translation patch please, the checksums of the outdated entries, and the expected checksums of the translation-patched entries

**Comment by Hydra-Spectre** [comment]
Name: Final Fantasy (J) T+Eng v1.3 Chaos Rush.nes
Size: 262160 bytes (256 KiB)
CRC32: 8C9209D9
CRC64: B1B00887C2AD2053
SHA256: 0328F50A61E7E1F31B389E2C1A196557EC8587FE7F165A62CF57917D86944A10
SHA1: 3D5642F102816589B5E9B0B47F4B24197AA14699
BLAKE2sp: E921A7B42EC7C63A17CE081203D990DB328BECF8119FA91C64CDDA0FF985D423

Name: Final Fantasy II (J) T+Eng v2.2b Chaos Rush.nes
Size: 262160 bytes (256 KiB)
CRC32: 310FD977
CRC64: CF5CEB2F97910C2B
SHA256: A3185EE81FFA195DB3ADB09454B79D329CFFA5DE8A0FAEF94B5FA273F230B56F
SHA1: FA278356A858994D5C037BD760D004D72FAD37B2
BLAKE2sp: 1C88E59C66D4AE5C69BA56A10039B6DDD17FD904DA69E29076F769FAA08AC99B

Name: Final Fantasy III (J) T+Eng v1.3 Chaos Rush.nes
Size: 524304 bytes (512 KiB)
CRC32: 9BF6E9C9
CRC64: 4645A20A83CEA741
SHA256: B1A95777B5B8CEE9866CE02C30D249EE4C8AC0BF435D769BB64C2184F641DE7E
SHA1: 9A1D40FC5BDAF3CCB513676C8A03066A1FCF4E54
BLAKE2sp: C5F98E817F5EFDF00A972BA29D4DC34CC7926033E00D6180BA7CBE7FE1904A03

**Comment by frederic-mahe** [comment]
Thanks @Hydra-Spectre 

@tjanas could you please have a look at these links? (if it fits with your ongoing work on the NES pack)

**Comment by tjanas** [comment]
I will take a look.
