### ISSUE TITLE
SNES: Final Fantasy IV Namingway, V GBA Script and VI TWUE outdated

### ISSUE THREAD

**Issue by Hydra-Spectre** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#310]

**Comment by tjanas** [comment]
Link to the translation patch please, and the checksums of the outdated entries

**Comment by frederic-mahe** [comment]
@Hydra-Spectre could you please help us identify both the correct patches and the ROMs to patch? otherwise, I will have to close that issue.

**Comment by Hydra-Spectre** [comment]
http://www.romhacking.net/hacks/2337/
Name: Final Fantasy IV (Hack) Namingway Edition v1.98b Rodimus Primal.sfc
Size: 1048576 bytes (1024 KiB)
CRC32: 26B5F1C6
CRC64: 623CDDCD5A3F847F
SHA256: 63BFAF7A97BF4A69650312BC7A4BC748501B99915953A23BD122FD9E3E2C98D3
SHA1: CD7E06522257FDCF4D60E36B4EC84023D70EE8B2
BLAKE2sp: B42FBE67A9A95CC2C1F071DAAA16FFFE1B9D0DABED83E9CB8701999A14666B82

http://www.romhacking.net/hacks/3687/
Name: Final Fantasy V (Hack) GBA Script Port v1.15+Ginger Battle Galuf+Bugfixes+Sprite Touch-Ups v1.02 J121.sfc
Size: 2621440 bytes (2560 KiB)
CRC32: 9053ED8A
CRC64: 053CF4A76F54F3CB
SHA256: 93647019C4F6A64BCBBDAA1450CCFA044F5DE40AE547B8971FD6D729E52472B8
SHA1: D1FFEDFC339CC37A60A11CE361F27A2509829FD9
BLAKE2sp: 221E474B02193F845DF0E0D3E5C240ED9DA43641F870327883652C6B8F8B6303

http://www.romhacking.net/hacks/1386/
Name: Final Fantasy VI (Hack) Ted Woolsey Uncensored Edition+Updated Opera+Bugfixes+Music Player Config 2+Optional Fixes Rodimus Primal.sfc
Size: 4194304 bytes (4096 KiB)
CRC32: 65AC5A5A
CRC64: 580E92DC76F0CAB1
SHA256: 5295C9783DE123797B66C67FFF4570472DDF4B5F5A4C790FE91C7451096CCE7D
SHA1: 69BA4C7EB79DA82B9F0945577C1D2A5090A8CEDD
BLAKE2sp: 83A4676701316621B1F2BD39365400D3611FEB546C69E950F587769159A815CD

**Comment by tjanas** [comment]
I will add these.

**Comment by tjanas** [comment]
@Hydra-Spectre I confirm your checksums for `Final Fantasy IV (Hack) Namingway Edition v1.98b Rodimus Primal.sfc`. However, I applied the three IPS patches included with `http://www.romhacking.net/hacks/3687/` (GBA Script on original rom, then Bugfiles and then Ginger on the patched rom), and I obtain a different checksum. I tried applying the latter two in vice-versa and still get the same result:
```
Size: 2621440 bytes (2560 KiB)
CRC32: ECF5AC83
CRC64: 5FD16D4D8468457C
SHA256: 2A86F35BB2DBEE527C19D0F67101BA2CF01CA0129E5CEB17CDAD839BADD120F4
SHA1: 5D505DBA013684D9EB101EECBEACB2F8A9E7A18D
BLAKE2sp: 2B2FAE03C22271F339DE3779AFA2EF52F36570BC1C2257597AFB1F8F627AB2A3
MD5: B5F1C93DBA7CFF2D39274F28382BDE71
```

**Comment by Hydra-Spectre** [comment]
@tjanas I also applied the Sprite Touch-Ups.

**Comment by tjanas** [comment]
Please provide the link(s) to all patches that need to be applied so I can recreate it.

**Comment by Hydra-Spectre** [comment]
http://www.romhacking.net/hacks/4537/

**Comment by tjanas** [comment]
It looks like this Sprite Touch-Ups patch was updated two days ago; could you resubmit your checksum for `Final Fantasy V (Hack) GBA Script Port+Ginger Battle Galuf+Bugfixes v1.15 J121, Sprite Touch-Ups v1.03 Chicken Knife.sfc`

**Comment by Hydra-Spectre** [comment]
I have a resubmitted checsum:
Name: Final Fantasy V (Hack) GBA Script Port+Ginger Battle Galuf+Bugfixes v1.15 J121, Sprite Touch-Ups v1.03 Chicken Knife.sfc
Size: 2621440 bytes (2560 KiB)
CRC32: C68BFA9E
CRC64: 5D02FD614E63E336
SHA256: 9CE5F69210CD69C7122200F9E2FE0C444AB81081E37F0817166DC224C388B11C
SHA1: AAFADBD212F230F2CD4C6EFF79BDEB64461B5313
BLAKE2sp: 523AE082B334F96A8AA3E335310B5125AAF4E118A0D34DC79CFB7D975593334F

**Comment by tjanas** [comment]
Fixed in [this](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/395) pull request.
