### ISSUE TITLE
NES: SD Gundam Gaiden - Knight Gundam Monogatari Translation ROM doesn't load

### ISSUE THREAD

**Issue by aberusugi** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#335]
Filename = SD Gundam Gaiden - Knight Gundam Monogatari (J) (V1.0) [T+Eng0.10_Assassin_Productions].nes

MD5 = D192B40A66AE24A9C311883CA64538C2

It won't load in MiSTer FPGA nor in Mesen, just green screen in Mesen and grey screen in MiSTer FPGA NES Core, therefore it's likely a patch mismatch that is the problem. I don't have an Everdrive for an NES to test in real hardware, maybe someone can help with that.

Important to note, Assassin Productions isn't found on romhacking.net, however...

http://www.romhacking.net/translations/5482/

This is a link to the current playable English Translation patch for the game. However, it has a specific SHA-1 ROM referenced.

https://datomatic.no-intro.org/?page=show_record&s=45&n=1914

However, bps and xdelta patches from the romhacking.net link above both fail in Beat and Xdelta on the non-Rev-1 game. Additionally, the non-rev1 in the current no-intro pack does not function (very garbled , so it must be a screwed up file for some reason that I have.

Proposed solution:

Apply this patch --> http://www.romhacking.net/translations/5482/ --> to ROM matching this description --> https://datomatic.no-intro.org/?page=show_record&s=45&n=1914

And all should be working properly after that, in theory.

**Comment by tjanas** [comment]
My solution would be to eliminate and not replace this translated rom from the SMDB (it only exists in Game Series Collections and not the main Translations directory). If you read the translation notes on the romhacking page, it says it will not work on real hardware and many emulators.

Here is info about non-Rev-1 source rom from [New Rising Sun's NES header database](https://forums.nesdev.com/viewtopic.php?f=3&t=19940&p=248796):

```
	<game><!-- Licensed Japan\SD Gundam 外伝 - Knight Gundam 物語 (rev0).nes -->
		<prgrom size="262144" crc32="146FB9C3" sha1="BCA657405B367EB52FC9E74E5534428A32027C8A" sum16="D3E7" />
		<chrrom size="131072" crc32="9E066029" sha1="3B129CE4B9C0CB47FD96B3EFCF2DF092DA05015C" sum16="C64B" />
		<rom size="393216" crc32="E170404C" sha1="94BD94C1DFC807074A3D6B319679E7E30E452693" />
		<prgnvram size="128" />
		<pcb mapper="159" submapper="0" mirroring="H" battery="1" />
		<console type="0" region="0" />
		<expansion type="1" />
	</game>
```
This matches the ROM checksum listed at romhacking, but doesn't match the file checksum; I believe this patch was made with the GoodNES version of this rom, which has the following incorrect header bytes:

GoodNES (mapper 16): `4E 45 53 1A 10 10 02 10 00 00 00 00 00 00 00 00`
```
SD Gundam Gaiden - Knight Gundam Monogatari (J) (V1.0) [!].nes
==============================================================
PRG: 16 (256KB)
CHR: 16 (256KB)
Mapper: 16
Mirroring: H
Format: NTSC
* 4-screen mirroring

Detailed information:
---------------------
MD5          : b6a052296f60d94903db6277fc267a62
CRC32        : a6d80b60
PRG CRC32    : 146fb9c3
CHR CRC32    : 9e066029
PRG+CHR CRC32: e170404c
```

Correct (mapper 159):   `4E 45 53 1A 10 10 F2 90 00 00 00 00 00 00 00 00`
```
SD Gundam Gaiden - Knight Gundam Monogatari (Japan).nes
=======================================================
PRG: 16 (256KB)
CHR: 16 (256KB)
Mapper: 159
Mirroring: H
Format: NTSC
* 4-screen mirroring

Detailed information:
---------------------
MD5          : b82de583dd6523d494467983fee82d16
CRC32        : 5d210db6
PRG CRC32    : 146fb9c3
CHR CRC32    : 9e066029
PRG+CHR CRC32: e170404c
```

I was able to apply the BPS patch successfully without errors, the output rom has the correct 159 mapper (although the battery-backed SRAM flag was turned off). However, the patched ROM failed to run correctly in Mesen. Per the patch notes:

```The ROM was expanded past its mapper limitation and will not work on hardware and most emulators. The latter issue is an easy fix that is encouraged to be reported to emulator devs to support the translation. The game like a lot of Bandai games, uses an EEPROM which is not supported by flashcarts and the only way of playing this on hardware would be to modify the original cart, but the ROM expansion kills that```

The patched ROM does run in FCEUmm.
![image](https://user-images.githubusercontent.com/20304619/85417418-31b41100-b535-11ea-9bfa-aacd8aeee822.png)
