### ISSUE TITLE
NES: Shinsenden Translation unplayable

### ISSUE THREAD

**Issue by aberusugi** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#336]
Filename: Shinsenden (J) [T+Eng].nes
MD5 = 2754340AA1341B81B100F1920D09F705
SHA-1 = 7F4A703DE5584024FDAA6D1DFFEE10BBAB75CC4C

This seems to be an alpha patch or a mispatch (patching intended for headered and was patched to a non-headered, for instance) of some sort, random characters, no english seen. Intro for company/producer is corrupted/black and white only, etc...

Steps taken to address this using this patch --> http://www.romhacking.net/translations/1420/

SM-Japanese SHA-1 = 706CF5478659F3CAAE163D8F500BB796D950CCD8
SM-Japanese SHA-1 Translation Patch Applied = 3D327D9D35568D70E7AA3A7CEACDB0E62DB0F457
No-intro-Japanese SHA-1 = 9725FF96E9BBFBA21D8B77C21D6CD1B5CBD0C19E
No-intro-Japanese SHA-1 Translation Patch Applied = 2A129270D019D0D61DB9DE6F34787EC2FBB33A44

Given that the SHA-1 of the file in the SM pack does not match the examples above, something is off, it might be some other patch other than the only one I know that is fully playable, it could be mispatch, etc...

The working version is...

Both the SmokeMonster original Japanese one newly patched and the No-Intro original Japanese one newly patched. So it looks like either version works.

Proposed solution:

Apply this patch - http://www.romhacking.net/translations/1420/ --> to the Shinsenden (Japan).nes file with SHA-1 of 706CF5478659F3CAAE163D8F500BB796D950CCD8  and update pack.

**Comment by tjanas** [comment]
Confirmed, will make a patch to update the pack.
