### ISSUE TITLE
SNES: mix of Super Star Wars ROMs (v 1.0 and 1.1)

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#34]
Hi @SmokeMonsterPacks 

(version 1.0) c6bd7239cb2074ff1c471d14535bead6290bba2d7c75b4f03209cb114877b4c8
```
SD2SNES/4 Betas, Prototypes, Revisions/Revisions/USA/Super Star Wars (USA).sfc
SD2SNES/4 Game Series Collections/Chronological/1992/1992-06-01 Super Star Wars (USA).sfc
SD2SNES/4 Game Series Collections/Genre/Run 'n' Gun/All Run 'n' Gun Games/Super Star Wars (USA).sfc
SD2SNES/4 Game Series Collections/Genre/Run 'n' Gun/Sort By - Side Scroll View/Super Star Wars (USA).sfc
```

The pack contains a version 1.1 of that ROM that is not listed on [byuu's preservation website](https://preservation.byuu.org/games/Lj4b/l7teQFeO), nor on [SNEScentral](http://snescentral.com/article.php?id=0062):

(version 1.1) 298b643fec4208f33d02a7afbb05c6f757b0086be533f8ca739466cbe96ae918
```
SD2SNES/1 US - S/Super Star Wars (USA) (Rev 1).sfc
SD2SNES/4 Game Series Collections/Best-Of Lists/Games That Defined the SNES - Racketboy.com/Honorable Mentions/Super Star Wars (USA) (Rev 1).sfc
SD2SNES/4 Game Series Collections/Franchise/Movie Based/Super Star Wars (USA) (Rev 1).sfc
SD2SNES/4 Game Series Collections/Genre/Platformer/Super Star Wars (USA) (Rev 1).sfc
SD2SNES/4 Game Series Collections/Miscellaneous/Mode 7 Graphics/Super Star Wars (USA) (Rev 1).sfc
```
It seems to me that the version 1.0 should be the one present in all folders, and that the version 1.1 should be in the `Revisions` folder only.

**Comment by SmokeMonsterPacks** [comment]
Byu's site and SNESCentral are less reliable than No-Intro. Rev 1 is the latest, so it's the one that goes in the official folder, while Rev 0 is older and is located in /Revisions.

**Comment by frederic-mahe** [comment]
OK, I understand the logic now.
