### ISSUE TITLE
Coverage Calculation is Flawed

### ISSUE THREAD

**Issue by FiZiX** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#357]
I noticed a bug in the coverage logic. Even if I point the build script at an empty folder, it will still say I have at least some level of coverage. This is what happened when I used "Turbo EverDrive & Super SD System 3 SMDB.txt" against an empty folder:

`processing file:         0 / 0

coverage: 805/1489 (54.06%)`

Is this due to there being many duplicate files in the Turbo EverDrive SMDB?

**Comment by frederic-mahe** [comment]
Thanks @FiZiX I'll look into that. The scripts desperately need unit tests to make them more robust, but testing in python is not my forte.

**Comment by frederic-mahe** [comment]
Coverage values for empty or very sparse input folders should be correct now (fix in commit https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/c1881f4e8e568b57256ca9843ba1bb3b759c6df5) Thanks @FiZiX !

**Comment by FiZiX** [comment]
Works great now! Thank you!
