### ISSUE TITLE
MegaSD: Spaces instead of tabs in line 7896 (Throne) in MegaSD SMDB.txt break build_pack.py

### ISSUE THREAD

**Issue by peterlanders** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#358]
Trying to build the MegaSD pack, was getting a 'not enough values to unpack' error. Scanned through the database file and found tabs in line 7896 replaced with spaces. Fixed it, build works fine again.

**Comment by peterlanders** [comment]
(I'm a Git amateur, didn't feel comfortable doing a pull request out of the blue!)

**Comment by frederic-mahe** [comment]
Thanks @peterlanders 

commit https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/4251aa0873a85a563884e3e5f522cf4cdba6c57f should fix the issue. I've checked, that issue was only present in the MegaSD pack.
