### ISSUE TITLE
Coleco: Choplifter bad dump

### ISSUE THREAD

**Issue by famiclone6502** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#359]
Once you start flying to the left and shooting, you'll see glitched graphics. The one from the Phoenix-AtariMax set on AtariAge version does not have this issue, and I've found overall that they have been a much more reliable source for good versions of Coleco games. (This issue occurs on both NT Mini Jailbreak firmware and MiSTer)

**Comment by tjanas** [comment]
Which pack? I’m pretty sure it was updated/fixed in one of them.

**Comment by famiclone6502** [comment]
The latest set I've found is "Colecovision - Atarimax 2019-11-30" and has the issue (CRC32 E7A1FF9F). The other one inside the MiSTer pack contains a Phoenix-AtariMax set that does not have the issue (CRC32 030E0D48), but it just contains the A-Z and by publisher.

**Comment by tjanas** [comment]
? The last update to the [Coleco pack](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/blob/master/EverDrive%20Pack%20SMDBs/Colecovision%20SMDB.txt) was three months ago, and it contains the correct checksum that you listed (`CRC32 030E0D48`):
`00a264f6237e357870a49dd086be36fea2525bf2f8fd8392a535c645d91a0af6	Colecovision Atarimax/COLECO/1 A-L Licensed/Choplifter! (USA).col	3a7e5ea50495a666bac8df0b3b2c82b5be65ad18	b3719118e9cfcc1234cd01c1e3fb84cf	030e0d48`

@frederic-mahe please close this issue
