### ISSUE TITLE
SD2SNES: Missing and out of date translations.

### ISSUE THREAD

**Issue by testbedangel** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#366]
Lot's of missing translations such as Shin Megami Tensei If... and Laplace no Ma (2.0) both by Aeon Genesis, both of which came out almost 2 years ago and out of date translations such Bishoujo Senshi Sailor Moon: Another Story being at v1.0 when v2.05 is out now. A quick read through romhacking.net's snes translations sorted by newest date first can help.

**Comment by frederic-mahe** [comment]
thanks @testbedangel 

could you please provide direct links to the translation patches? and the checksums of the outdated entries. It would help us identify both the correct patches and the ROMs to patch.

**Comment by testbedangel** [comment]
shin megami tensei if...: https://www.romhacking.net/translations/3951/

Laplace no Ma: https://www.romhacking.net/translations/308/

Bishoujo Senshi Sailor Moon - Another Story:  https://www.romhacking.net/translations/4654/

You can see all the checksums under the ROM / ISO Information at each of the links. There are lots of games that need to be updated to the newest patches though.
