### ISSUE TITLE
Nt Jailbreak mislabled entries

### ISSUE THREAD

**Issue by Jayde6** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#37]
Looking at the latest Nt Jailbreak SMDB file I notice that 4 of the Mapper 185 fixed entries are labeled (USA).

Mighty Bomb Jack
Othello
Seicross
Spy vs Spy

I remember reading on a forum a while back that Great Hierophant had said only 9 Famicom games used mapper 185. The other 5 on your list are labeled (Japan).

I know the USA release of Spy vs Spy runs correctly on the Nt Mini, both original cart and by using copynes to an sdcard. It also has an additional splash screen and different year of release date on the title screen so I know it's not a case of same rom being used for both countries. No idea on the others.

**Comment by SmokeMonsterPacks** [comment]
I believe these were sent to me by The Great Hierophant, so I will keep them. It's no big deal if they're mislabeled, but I don't want to purge them prematurely.

**Comment by Jayde6** [comment]
Here's a link to that forum post where Great Hierophant says there were only 9 Japanese games with mapper 185, in case you want to fix those USA labels to Japan. For proper information and documentation sake.

https://forums.nesdev.com/viewtopic.php?f=9&t=16722

**Comment by tjanas** [comment]
> Here's a link to that forum post where Great Hierophant says there were only 9 Japanese games with mapper 185, in case you want to fix those USA labels to Japan. For proper information and documentation sake.
> 
> https://forums.nesdev.com/viewtopic.php?f=9&t=16722

Thank you for this documentation, it confirms the issue and I made the four filename fixes.

**Comment by frederic-mahe** [comment]
Thanks @Jayde6 and @tjanas !
