### ISSUE TITLE
Corrections for SMDB Packs

### ISSUE THREAD

**Issue by Jayde6** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#38]
--------------------------------------------------------------------------------------------------------------
*** All non duplicate hash corrections from the comments have been placed in this top post ***
--------------------------------------------------------------------------------------------------------------

Hopefully this is the right place to report this stuff,

In addition to the Nt Jailbreak entries (issue #37) I found these as well;

----------------------------------------------
EverDrive 64 & 64drive SMDB
----------------------------------------------

*wrong section*

	EverDrive 64/1 US - A-M/Doubutsu no Mori (J) [T+Eng2010-12-02_Zoinkity].z64
	EverDrive 64/1 US - A-M/F1 Racing Championship (Brazil) (En,Fr).z64
	EverDrive 64/2 Japan - A-Z/F1 Racing Championship (B) (M2).z64

----------------------------------------------
EverDrive GB SMDB
----------------------------------------------

*wrong section*

	EverDrive GB/1 Game Boy Color/2 Unlicensed - A-Z/Pooh And Tigger's Hunny Safari (Hack 1) (Fast Intro Screens, Unlimited Lives).gbc
	EverDrive GB/1 Game Boy Color/2 Unlicensed - A-Z/Pooh And Tigger's Hunny Safari (Hack 2) (Fast Intro Screens, Unlimited Lives, Honey X2).gbc
	EverDrive GB/1 Game Boy Color/2 Unlicensed - A-Z/Pooh And Tigger's Hunny Safari (Hack 3) (Fast Intro Screens, Unlimited Lives, Honey X2, Invincibility)

*possible wrong section some unlicensed game translations are in translations folder, these aren't*

	EverDrive GB/1 Game Boy Color/2 Unlicensed - A-Z/Metal Slug (Unl) [C][T+Eng].gbc
	EverDrive GB/1 Game Boy Color/2 Unlicensed - A-Z/Metal Slug 2001 (Unl) [C][T+Eng].gbc
	EverDrive GB/1 Game Boy/2 Unlicensed - A-Z/Sonic 6 (Unl) [T+Spa1.0_Ereza].gb
	EverDrive GB/1 Game Boy/2 Unlicensed - A-Z/Sonic 6 (Unl) [T+Spa100%_Tanero].gb

----------------------------------------------
Turbo EverDrive & Super SD System 3 SMDB
----------------------------------------------

*wrong section*

	Turbo EverDrive/2 PC Engine - A-M/1941 - Counter Attack (J) (SGX) [h1] (no SGX).pce
	Turbo EverDrive/3 SuperGrafx/Aldynes Enhanced (J) MIJET Bug Fix Beta

----------------------------------------------
EverDrive N8 & PowerPak SMDB
----------------------------------------------

*wrong section*

	EverDrive N8/4 Betas, Prototypes, Revisions/Betas/Adventures of Bayou Billy, The (U) [T+Fre-Beta_ks151].nes
	EverDrive N8/4 Betas, Prototypes, Revisions/Betas/Akira (J) [a1][T+Eng_Chocoman].nes
	EverDrive N8/4 Betas, Prototypes, Revisions/Betas/Castlevania Retold V2.0 (Beta Cross Pickup) (CV PRG0 Hack).nes
	EverDrive N8/4 Betas, Prototypes, Revisions/Betas/Dragon Ball 3 - Gokuu Den (J) [a1][T+Eng0.15_Dodgy].nes
	EverDrive N8/2 Unlicensed - A-Z/Selections/Kart Fighter (Unl) [T+Eng1.00_DvD Translations].nes
	EverDrive N8/2 Japan - A-Z/Japan P-S/Rockman 3  Improvement v2.01 (J).nes
	EverDrive N8/4 Betas, Prototypes, Revisions/Revisions/2 Later Revisions/Solar Wars 2001 (Homebrew).NES
	EverDrive N8/2 Unlicensed - A-Z/1 Unlicensed S-Z/Sonic The Hedgehog - Bugfix (Hack) (Unl) [f1].nes
	EverDrive N8/2 Unlicensed - A-Z/1 Unlicensed S-Z/Sonic The Hedgehog Improvement (Hack) Somari v1 the jabu.nes
	EverDrive N8/1 US - R-Z/Super Mario Bros. 2 (USA) Improvement SpiderDave 20151023.nes

*should be F-15*
	
	EverDrive N8/2 Unlicensed - A-Z/1 Unlicensed A-K/F15 City War (USA) (v1.1) (Unl).nes

*only revision*

	EverDrive N8/4 Betas, Prototypes, Revisions/Revisions/2 Later Revisions/Dragon Ball - Le Secret du Dragon (France) (Rev A).nes

----------------------------------------------
Super EverDrive & SD2SNES SMDB
----------------------------------------------

*wrong section*

	SD2SNES/1 US - S/Super Bomberman 4 English (J) T+Eng.smc
	SD2SNES/2 Japan - A-Z/Japan S-Super Final/Super Double Dragon Trained (Hack).sfc
	SD2SNES/2 Japan - A-Z/Japan S-Super Final/Sunset Riders Trained (Hack).sfc

*there is a Rev 1 in that folder already*

	SD2SNES/2 Other Regions - A-Z/Germany/Terranigma (Germany).sfc

*Prototype listed in main folder*

     SD2SNES/1 US - A-E/Batman - Revenge of the Joker (U).smc

----------------------------------------------
Mega EverDrive Pack
----------------------------------------------

*Alternate version in same folder*

     Mega EverDrive/2 Japan - A-Z/Japan - P-Z/Rockman - Mega World (Japan) (Alt 1).md
     Mega EverDrive/2 Japan - A-Z/Japan - P-Z/Rockman - Mega World (Japan).md

*not sure the exact ruleset you organize with, these are in both unlicensed and in hacks*
	
	Balloon Boy (Unl) [f1]
	Bug's Life, A (Unl) [f1]
	Earth Defend, The (Unl) [f1]
	Funny World (Unl) [f1]
	King of Fighters 99 (Unl) [f1]
	Mahjong Lover (Ch) (Unl) [f1]
	Onslaught - TMSS Bypass Patch (Unl) v1 Keeper7
	Pocket Monsters (Unl) [f1]
	Pocket Monsters 2 (Unl) [f1]
	Pokemon Stadium (Unl) [f1]
	Rockman X3 (Unl) [f1]
	Soul Blade (Unl) [f1]
	Soul Edge VS Samurai Spirits (Unl) [f1]
	Super Bubble Bobble MD EverDrive Fixed (Unl)
	Super Donkey Kong 99 (Unl) [f1]
	Super Mario 2 1998 (Unl) [f1]
	Super Mario Bros. (Unl) [f1]
	Super Mario World (Unl) [f1]
	Super Mario World 64 (Unl) ED Patched [f1]
	Top Fighter 2000 MK VIII (Unl) [f1]

*this is in unlicensed, protoypes and in hacks*

	Sonic and Crackers EverDrive Patched (Unl) (Proto)

**Comment by SmokeMonsterPacks** [comment]
Thanks so much @Jayde6! I'll get all of these fixed in the next updates. I really appreciate the help :D

**Comment by Jayde6** [comment]
No problem, thank you both for all the things you guys do. 
I'll keep an eye out for more, speaking of which;

`SD2SNES/2 Other Regions - A-Z/Germany/Terranigma (Germany).sfc`

there is a Rev 1 in that folder already.

**Comment by Jayde6** [comment]
*same hashes*

	Mega EverDrive/2 Japan - A-Z/Japan - A-O/Killing Game Show, The (Japan).md
	Mega EverDrive/4 Hacks/Hacks A-Z/Killing Game Show - 1993 Remix (Hack).bin

	Mega EverDrive/1 US - G-P/Phantasy Star III - Generations of Doom (USA, Europe).md
	Mega EverDrive/2 Europe - A-Z/1 PAL - M-R/Phantasy Star III - Generations of Doom (USA, Europe).md
	(makes sense for these two to be the same but I included both in case they are all the hack)
	Mega EverDrive/4 Hacks/Hacks A-Z/Phantasy Star 3 - Enemy Formation Edits (Hack) v1 Gavin the Demon.md

	Mega EverDrive/1 US - Q-Z/Tatsujin ~ Truxton (World).md
	Mega EverDrive/4 Hacks/Hacks A-Z/Truxton Arcade Colors (Hack) v1 fusaru.bin

*not sure the exact ruleset you organize with, these are in both unlicensed and in hacks*
	
	Balloon Boy (Unl) [f1]
	Bug's Life, A (Unl) [f1]
	Earth Defend, The (Unl) [f1]
	Funny World (Unl) [f1]
	King of Fighters 99 (Unl) [f1]
	Mahjong Lover (Ch) (Unl) [f1]
	Onslaught - TMSS Bypass Patch (Unl) v1 Keeper7
	Pocket Monsters (Unl) [f1]
	Pocket Monsters 2 (Unl) [f1]
	Pokemon Stadium (Unl) [f1]
	Rockman X3 (Unl) [f1]
	Soul Blade (Unl) [f1]
	Soul Edge VS Samurai Spirits (Unl) [f1]
	Super Bubble Bobble MD EverDrive Fixed (Unl)
	Super Donkey Kong 99 (Unl) [f1]
	Super Mario 2 1998 (Unl) [f1]
	Super Mario Bros. (Unl) [f1]
	Super Mario World (Unl) [f1]
	Super Mario World 64 (Unl) ED Patched [f1]
	Top Fighter 2000 MK VIII (Unl) [f1]

*this is in unlicensed, protoypes and in hacks*

	Sonic and Crackers EverDrive Patched (Unl) (Proto)

**Comment by Jayde6** [comment]
----------------------------
Everdrive N8
----------------------------

*duplicate, same hash*

	EverDrive N8/1 US - A-F/California Games (U) [!].nes
	EverDrive N8/1 US - A-F/California Games (USA).nes

**Comment by frederic-mahe** [comment]
Hi @Jayde6. I tried to build on your findings and I wrote a tool to detect duplicates (same hash, same folder). The results for N8 are listed in issue #39.

**Comment by Jayde6** [comment]
--------------------------
SD2SNES
--------------------------

Prototype listed in main folder

     SD2SNES/1 US - A-E/Batman - Revenge of the Joker (U).smc

**Comment by frederic-mahe** [comment]
# Everdrive N8

I wrote a new script that can detect files with the same hash present in different alphabetical folders. Some of the cases listed below could be legit, I am not sure.

**Japan**
```
8ffdb9345b58913264d7c38c6872b5beb769473bf43f7dad1f9fbaafa1c1aa9f	EverDrive N8/2 Japan - A-Z/Japan E-J/Future Wars - Mirai Senshi Lios (Japan).nes
8ffdb9345b58913264d7c38c6872b5beb769473bf43f7dad1f9fbaafa1c1aa9f	EverDrive N8/2 Japan - A-Z/Japan K-O/Mirai Senshi - Lios (Japan).nes
```

**US**
```
4c83b6150e3cde4f0e463e4d1e51b78452d72131c675d9b33df9c65cb9604a14	EverDrive N8/1 US - A-F/Battle Tank (U) [!].nes
4c83b6150e3cde4f0e463e4d1e51b78452d72131c675d9b33df9c65cb9604a14	EverDrive N8/1 US - G-Q/Garry Kitchen's BattleTank (USA).nes

8e32ae844f18a7f0c0e7731c1e620d2fbfcf1490eefbe707b664d63cd13a6eed	EverDrive N8/1 US - A-F/California Games (U) [!].nes
8e32ae844f18a7f0c0e7731c1e620d2fbfcf1490eefbe707b664d63cd13a6eed	EverDrive N8/1 US - A-F/California Games (USA).nes

9bdc5585a94368bdf3b038900024d83a529c8ab0bcfacd1c64681b4980fe61a6	EverDrive N8/1 US - A-F/Chris Evert & Ivan Lendl in Top Players' Tennis (USA).nes
9bdc5585a94368bdf3b038900024d83a529c8ab0bcfacd1c64681b4980fe61a6	EverDrive N8/1 US - R-Z/Top Players' Tennis - Featuring Chris Evert & Ivan Lendl (U) [!].nes	

a9880bb4dc249b0d191c2e6deea0c61cfb8b52f5e4c86db21f26af354d328cb5	EverDrive N8/1 US - R-Z/T&C 2 - Thrilla's Surfari (U) [!].nes
a9880bb4dc249b0d191c2e6deea0c61cfb8b52f5e4c86db21f26af354d328cb5	EverDrive N8/1 US - R-Z/Town & Country Surf Designs - Thrilla's Surfari (USA).nes

fbc97509e900f52142360e421b0773bcab6eea423186e2528ac4540f97272acd	EverDrive N8/1 US - A-F/Capcom's Gold Medal Challenge '92 (USA).nes
fbc97509e900f52142360e421b0773bcab6eea423186e2528ac4540f97272acd	EverDrive N8/1 US - G-Q/Gold Medal Challenge '92 (U) [!].nes
```

No hit in the `2 Europe` or `2 Unlicensed` folders.

**Comment by Jayde6** [comment]
Looking at box art, wikipedia, and other sources it looks like most of these are confusion by who ever dumped them as to how to exactly name them:

     EverDrive N8/2 Japan - A-Z/Japan K-O/Mirai Senshi - Lios (Japan).nes

Is correct of the two as Mirai Senshi translates to future wars and there is no english on the box

     EverDrive N8/1 US - G-Q/Garry Kitchen's BattleTank (USA).nes

Looks to be the complete title going of box and cart, title screen is just Battle Tank

     EverDrive N8/1 US - A-F/California Games (U) [!].nes
     EverDrive N8/1 US - A-F/California Games (USA).nes

No difference

     EverDrive N8/1 US - A-F/Chris Evert & Ivan Lendl in Top Players' Tennis (USA).nes

Full title on the US box and title screen

     EverDrive N8/1 US - R-Z/Town & Country Surf Designs - Thrilla's Surfari (USA).nes

It is the sequel but there is no 2 on the box, its written as this one, the copyright screen has it as T&C 2 but the title screen is the same as the box and cart label

     EverDrive N8/1 US - A-F/Capcom's Gold Medal Challenge '92 (USA).nes

Box and title screen put Capcom's in the title

**Comment by Jayde6** [comment]
Alternate version in same folder

     Mega EverDrive/2 Japan - A-Z/Japan - P-Z/Rockman - Mega World (Japan) (Alt 1).md
     Mega EverDrive/2 Japan - A-Z/Japan - P-Z/Rockman - Mega World (Japan).md

**Comment by Jayde6** [comment]
Checking some stuff after seeing issue #61,

     EverDrive N8/4 Game Series Collections/Developer/Developer HAL/Kirby's Adventure (Canada).nes

Only exists in game series collections

**Comment by frederic-mahe** [comment]
@Jayde6 hum, that's an interesting idea. The `Game Series Collections` are curated by @tjstogy, and there could be differences with what @SmokeMonsterPacks did. Regarding `Kirby's Adventure`, the `Game Series Collections` seems to be mixing two US revisions of the game in its `Best-Of Lists`:
```sh
grep Kirby EverDrive\ N8\ \&\ PowerPak\ SMDB.txt | cut -f1,2 | sort -k1,1d | grep -vi "Hack" | less -S
```
```
34afcebaf04d57a42c2436fb95b933c7841e1621f1dc3be482380baef33ec3d8        EverDrive N8/1 US - G-Q/Kirby's Adventure (USA) (Rev A).nes
34afcebaf04d57a42c2436fb95b933c7841e1621f1dc3be482380baef33ec3d8        EverDrive N8/4 Betas, Prototypes, Revisions/Revisions/2 Later Revisions/Kirby's Adventure (USA) (Rev A).nes
34afcebaf04d57a42c2436fb95b933c7841e1621f1dc3be482380baef33ec3d8        EverDrive N8/4 Game Series Collections/Best-Of Lists/Games That Defined the NES - Racketboy.com/Kirby's Adventure (USA) (Rev A).nes
34afcebaf04d57a42c2436fb95b933c7841e1621f1dc3be482380baef33ec3d8        EverDrive N8/4 Game Series Collections/Best-Of Lists/Games That Pushed the Hardware Limits - Racketboy.com/Kirby's Adventure (USA) (Rev A).
34afcebaf04d57a42c2436fb95b933c7841e1621f1dc3be482380baef33ec3d8        EverDrive N8/4 Game Series Collections/Best-Of Lists/Top 10 Games to Play Today - Snackbar-games.com/Kirby's Adventure (USA) (Rev A).nes
34afcebaf04d57a42c2436fb95b933c7841e1621f1dc3be482380baef33ec3d8        EverDrive N8/4 Game Series Collections/Best-Of Lists/Top 10 Platformers - ArcadeSushi.com/Kirby's Adventure (USA) (Rev A).nes
34afcebaf04d57a42c2436fb95b933c7841e1621f1dc3be482380baef33ec3d8        EverDrive N8/4 Game Series Collections/Best-Of Lists/Top 10 Platformers - Cygnus Destroyer (YouTube)/06 Kirby's Adventure (USA) (Rev A).nes
34afcebaf04d57a42c2436fb95b933c7841e1621f1dc3be482380baef33ec3d8        EverDrive N8/4 Game Series Collections/Best-Of Lists/V's Recommended Games - 4chan/NES/Kirby's Adventure (USA) (Rev A).nes
34afcebaf04d57a42c2436fb95b933c7841e1621f1dc3be482380baef33ec3d8        EverDrive N8/4 Game Series Collections/Developer/Developer HAL/Kirby's Adventure (USA) (Rev A).nes
34afcebaf04d57a42c2436fb95b933c7841e1621f1dc3be482380baef33ec3d8        EverDrive N8/4 Game Series Collections/Genre/Platformers/Kirby's Adventure (USA) (Rev A).nes

56901e11f6fe812e0a049c747fa0b0d6fc42a336c502ca94fb5282229853347d        EverDrive N8/2 Japan - A-Z/Japan E-J/Hoshi no Kirby - Yume no Izumi no Monogatari (Japan).nes
56901e11f6fe812e0a049c747fa0b0d6fc42a336c502ca94fb5282229853347d        EverDrive N8/4 Game Series Collections/Developer/Developer HAL/Hoshi no Kirby - Yume no Izumi no Monogatari (Japan).nes
56901e11f6fe812e0a049c747fa0b0d6fc42a336c502ca94fb5282229853347d        EverDrive N8/4 Game Series Collections/Miscellaneous/Nintendo Classic Mini 2016 Pack-ins/Mini Famicom Classic Edition/Hoshi no Kirby - Yume

572f2715884f8dfed05ff9b40677b1637bc9b73835f0423a6bde0f82a389f66e        EverDrive N8/4 Game Series Collections/Developer/Developer HAL/Kirby's Adventure (Canada).nes

979247b30dc94a8e305b430725376a47d3db265e7ff45b271368c300b493f8c0        EverDrive N8/2 Europe - A-Z/PAL A-M/Kirby's Adventure (Europe).nes


b0d74f4270ad5855f10224c460956f6dfe41d6673a38262ad0d37aa9ce103dd5        EverDrive N8/4 Betas, Prototypes, Revisions/Revisions/1 Original Release Versions/Kirby's Adventure (USA).nes
b0d74f4270ad5855f10224c460956f6dfe41d6673a38262ad0d37aa9ce103dd5        EverDrive N8/4 Game Series Collections/Best-Of Lists/Top 100 List - GameFAQs.com/014 Kirby's Adventure (USA).nes
b0d74f4270ad5855f10224c460956f6dfe41d6673a38262ad0d37aa9ce103dd5        EverDrive N8/4 Game Series Collections/Best-Of Lists/Top 100 List - Retro-Sanctuary.com/004 Kirby's Adventure (USA).nes
b0d74f4270ad5855f10224c460956f6dfe41d6673a38262ad0d37aa9ce103dd5        EverDrive N8/4 Game Series Collections/Best-Of Lists/Top 100 List - satoshimatrix.wordpress.com/010 Kirby's Adventure (USA).nes
b0d74f4270ad5855f10224c460956f6dfe41d6673a38262ad0d37aa9ce103dd5        EverDrive N8/4 Game Series Collections/Developer/Developer HAL/Kirby's Adventure (USA).nes
b0d74f4270ad5855f10224c460956f6dfe41d6673a38262ad0d37aa9ce103dd5        EverDrive N8/4 Game Series Collections/Miscellaneous/Nintendo Classic Mini 2016 Pack-ins/NES Classic Edition/Kirby's Adventure (USA).nes
```

**Comment by Jayde6** [comment]
@frederic-mahe I'm seeing more and more duplicate hashes shared between the main folders and hacks, translations, etc. such as;
     
     SD2SNES/2 Europe - A-Z/PAL - S-Z/Star Trek - Deep Space Nine - Crossroads of Time (Europe).sfc
     SD2SNES/4 Translations/Non-English/Spanish/Star Trek - Deep Space Nine - Crossroads of Time (E).smc

     SD2SNES/1 US - S/Star Trek - Deep Space Nine - Crossroads of Time (USA).sfc
     SD2SNES/4 Translations/Non-English/Spanish/Star Trek - Deep Space Nine - Crossroads of Time (U) [!].smc

     SD2SNES/2 Europe - A-Z/PAL - A-J/FIFA - Road to World Cup 98 (Europe) (En,Fr,De,Es,It,Sv).sfc
     SD2SNES/4 Hacks/PAL-to-NTSC 60Hz Patched/FIFA - Road to World Cup 98 PAL-to-NTSC Patched (Europe) v1 GhostlyDark.sfc

There's quite a few more of these, as well as the ones I found in the Genesis pack. Would you be able to adapt your scripts to search the main folders (US, Europe, Japan, Other Regions) against Unlicensed, Betas, Prototypes & Revisions, Hacks, Homebrew, Translations?

**Comment by frederic-mahe** [comment]
@Jayde6 sure, I should be able to script crossed-searches. However, would you consider putting that on hold for a few weeks? @SmokeMonsterPacks will be traveling for a while and he will not tackle these issues until mid-July. And I would not want him to feel swamped by the task of cleaning all the issues we've spotted. I know to well how work can accumulate to a point where one doesn't know where to start anymore.

**Comment by Jayde6** [comment]
Absolutely. I would not want him feeling swamped either, not to mention I've made a lot of work for you as well this past month, with all the scripts. You have the info on what can be fixed and you guys know best how to tackle it and at what pace. 

If I see anything else I'll make a note of it but won't add it to the github until he's back and it seems appropriate. Although at this point I can't think of anything else left to find ha.

In the meantime I'm going to clean this post up and put all the relevant info in the first post of this issue, that way when he's ready he doesn't have to read through the whole thread looking for stuff. I'll also delete the duplicate hash stuff from this thread as they will eventually be listed in yours when it's time to run the rest of your scripts.

Thanks again to you both, I hope I wasn't overzealous.

**Comment by frederic-mahe** [comment]
thanks @Jayde6 ! Your contribution is really appreciated :-)

**Comment by tjanas** [comment]
@frederic-mahe I am working on this.

**Comment by tjanas** [comment]
@Jayde6 @frederic-mahe please review pull request https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/163

**Comment by frederic-mahe** [comment]
It seems everything above has been fixed by @tjanas or moved to a new issue.
