### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by actraiser30** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#396]
Hello is there anywhere the changelog for the packs?

thanks

**Comment by frederic-mahe** [comment]
hi @actraiser30 there is no synthetic changelog, as far as I know.

However, you can check the history of changes for any given pack. For instance, here is the [history of commits for the SNES pack](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commits/master/EverDrive%20Pack%20SMDBs/Super%20EverDrive%20%26%20SD2SNES%20SMDB.txt). Commit titles and descriptions should give you an idea of what changed.

**Comment by symbios24** [comment]
Thanks
Another thing is in the NES pack the Pal folder has 300 to 400 roms and the usa folder has almost 800 roms,they are missing roms from the pal folder like the guarella war and many others
Can you include the missing games/roms to the pal folder?

**Comment by tjanas** [comment]
US is missing roms that are in PAL folder? Or vice-versa? I think the convention is that if a rom exists in USA, it doesn’t get duplicated in Europe/Japan if it’s also from those regions. Also, (World) roms usually go in US only, unless it is language-specific. I could be wrong though.

**Comment by symbios24** [comment]
Pal are missing roms,can you put the missing roms in the pal folder?
If you cannot,can you at least rename the world versions in the usa folder to usa-europe or usa-world?

**Comment by tjanas** [comment]
I’m 99% sure all roms in the main directories are already named to no-intro naming standards. Also pretty sure we have virtually 100% coverage of NES no-intro (perhaps minus a few recent virtual console additions).

**Comment by symbios24** [comment]
Strange what i mean is for example the rom guarella war also exist in pal but its not in the pal folder,it is in tbe usa folder,if you cannot add them in the pal section can you at least give me the list of the world games included in the usa folder to add them my self?
Thanks

**Comment by frederic-mahe** [comment]
@symbios24 are you sure the PAL ROM you are looking for is not in the PAL folder? I see a `2 Europe - A-Z/Europe A-M/Guerrilla War (Europe).nes` that is different from the NTSC US version.

**Comment by symbios24** [comment]
Strange i could not find it,but its not this the issue the thing is the usa folder/s have more tha 800 games while the pal folders have almost 400 games why so little?

**Comment by frederic-mahe** [comment]
My interpretation is that there were only 400 games that were actually designed or modified to run on PAL systems. There rest of the games distributed in PAL regions were exact copies of NTSC games. As tjanas indicated, you can select all the games with "(World)" or "(USA Europe)" in their names and copy them to the Europe folder.

**Comment by actraiser30** [comment]
they are only 14 games in the usa folder with USA Europe name

**Comment by frederic-mahe** [comment]
Yes, and `10-Yard Fight` is present in both the US and Europe folders:
```
1 US - A-F/10-Yard Fight (USA, Europe).nes
2 Europe - A-Z/Europe A-M/10-Yard Fight (USA, Europe).nes
```
And there are 15 `(World)` games in total.

**Comment by symbios24** [comment]
Thanks
Any change that you can put all contra games official and unofficial in the game series collection ? I think all together they are 8
Contra 1-8  and also all hacks in the hacks folder?

**Comment by frederic-mahe** [comment]
@symbios24 could you please open a new issue for the Contra games? The initial topic of this issue was about changelog.
