### ISSUE TITLE
windows - exception on path too long 

### ISSUE THREAD

**Issue by leandromacrini** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#40]
To handle the exception correctly on build_pack.py, the line 98 should be:
copy_fn(source, fixed_dest)

and not:
copy_fn(absolute_filename, fixed_dest)

because absolute_filename doesn't exists

**Comment by frederic-mahe** [comment]
Thanks @leandromacrini !

I've pushed a patch to correct this bug (commit [e561e41a0d](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/e561e41a0deeba2138d157637f08bca87aeea152)).
