### ISSUE TITLE
Why the 2 versions of NES roms?

### ISSUE THREAD

**Issue by johhenrik** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#405]
I understand that there is a difference between the headers, but why does the pack have to include both versions? Wouldn't one want the v2 headers only, which are "more correct"? Or have misunderstood something perhaps?

**Comment by johhenrik** [comment]
and I guess I can answer that question myself, when I browsed around other issues. :) I saw that PowerPak and NT mini needs v1 headers. So I would assume that is why. :)

**Comment by tjanas** [comment]
The pack doesn't have to include both versions. Complete v2 headers are not supported on the Analogue Nt Mini, unless the last two bytes in the NES2.0 headers are set to null bytes. And yes, PowerPak does not support NES2.0 headers at all. @frederic-mahe close this issue please.
