### ISSUE TITLE
EverDrive GG: Remove SG-1000 

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#453]
SG-1000 was moved to Master EverDrive smdb. This GG `3 Sega SG-1000 Computer Videogame` directory should be an empty placeholder directory to be populated from the Master EverDrive, and EverDrive GG's SG-1000 subdirectories under `4 Betas, Prototypes, Revisions` should be removed.

**Comment by steve1515** [comment]
I'm going to agree with this. It should be removed from the GG pack.

**Comment by tjanas** [comment]
Instead of having to extract SG-1000 folder(s) from the SMS SMDB, I made a [standalone SG-1000 smdb](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/blob/master/EverDrive%20Pack%20SMDBs/Sega%20SG-1000%20SMDB.txt) that can be dropped into placeholder directories for the EverDrive GG, Master EverDrive, Mega Sg, or Nt Mini.

**Comment by tjanas** [comment]
Resolved via https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/483
