### ISSUE TITLE
Remove EverDrive OS from Master EverDrive Pack

### ISSUE THREAD

**Issue by steve1515** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#457]
The _Master EverDrive/SMSSYS/SMSOS.sms_ file should probably be removed from the Master EverDrive pack to line up with the other packs.

**Comment by tjanas** [comment]
Fixed in https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/473
