### ISSUE TITLE
SNES: "Game Series Collections/Best-Of Lists" no longer contains "V's Recommended Games" folders

### ISSUE THREAD

**Issue by rgdelato** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#487]
One of my older versions of the SNES pack includes two folders that no longer exist in the most up-to-date pack, and it doesn't seem like they were removed intentionally?

`4 Game Series Collections/Best-Of Lists/V's Recommended Games JP - 4chan`
`4 Game Series Collections/Best-Of Lists/V's Recommended Games USA - 4chan`

**Comment by tjanas** [comment]
How old is your pack? I looked at the SMDB from [over 2 years ago](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/blob/9388e4fcd21ff33f6e614792b559fb1730fceecd/EverDrive%20Pack%20SMDBs/Super%20EverDrive%20%26%20SD2SNES%20SMDB.txt) and those aren't present there either.

**Comment by tjanas** [comment]
Looks like they were removed from GSC in April 2018 with [this commit](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/blob/c4960351c9248516e58c094d569861eabbf15097/EverDrive%20Pack%20SMDBs/Super%20EverDrive%20%26%20SD2SNES%20SMDB.txt). Maybe @tjstogy or @SmokeMonsterPacks can explain the reasoning.

**Comment by steve1515** [comment]
Is there a policy on requiring commit messages? We should probably have one if we don't so we can keep track of what's changed and why things were done.

**Comment by tjanas** [comment]
Yes, I believe commit messages and documentation in pull request are important.

**Comment by SmokeMonsterPacks** [comment]
V's Lists were pulled from all packs I believe last year. Mainly to save space since they were huge.

**Comment by rgdelato** [comment]
For what it's worth, part of the reason I'd noticed it in the first place is because V's list still seems to be in just about every pack /except/ the SNES pack (NES, Genesis, TG16, MS, GG, GB, etc), so I had assumed the removal from the SNES pack was a mistake.
