### ISSUE TITLE
Bin files replaced by cuefile when decompressing from zip on OS X

### ISSUE THREAD

**Issue by evan** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#502]
I am using OS X 10.15.7 with the built-in Python3. 

When I run `build_pack.py` against a group of zipped bin/cues, the script appears to decompress them, but then overwrites each binfile with the cue file. 

If I decompress the zipfiles into folders first it works fine.

**Comment by frederic-mahe** [comment]
Thanks @evan 

I think this is related to issue #520, which is now fixed (commit 1ef394a4a8320ee81a4676c3a3593d14329f7621) thanks to @hotelvictorcharlie 

@evan could you please try with the new `build_pack.py`?

**Comment by evan** [comment]
That does indeed look like the fix. I will close for now and re-open if I have further problems.
