### ISSUE TITLE
Mega Everdrive: Missing Unlicenced

### ISSUE THREAD

**Issue by adlroux** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#518]
Some games have been removed from the previous packs lists, didnt they? Namely Pier Solar and Xeno Crisis. Is this on purpose, or is it just a little oversight?

Thank you very much, keep up the good work!

**Comment by frederic-mahe** [comment]
Hi Adélaïde, yes we've decided to exclude games from active indie studios (except public demos and open-source games).

**Comment by adlroux** [comment]
@frederic-mahe Thank you for the answer, this is fair enough.  Any idea of which particular roms were excluded?

**Comment by frederic-mahe** [comment]
Sure, for the MegaDrive the following games were excluded:
- Ultracore
- Tanglewood
- Xeno Crisis

**Comment by frederic-mahe** [comment]
I am going to close that issue. Feel free to re-open if you have more questions.
