### ISSUE TITLE
Comic Bakery SGM (2014 Collectorvision Games).bin is a fake dump

### ISSUE THREAD

**Issue by hotelvictorcharlie** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#522]
The rom `Comic Bakery SGM (2014 Collectorvision Games).bin` (in `Colecovision SMDB.txt`) should be removed, because it's not a real dump. It's just 32KB of FF bytes and nothing else.

**Comment by tjanas** [comment]
Confirmed.
