### ISSUE TITLE
N64 hashes incorrect for 3 files?

### ISSUE THREAD

**Issue by Infinitum8t** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#533]
These are the hashes I've found for the following 3 files in previous packs going back to 2018, Github, and hack:
They don't match the hashes from the current SMDB pack file. Can you please confirm?

Controller Test Tool (PD) sanni 2012.z64
F5171AB1E18BF6DD5F3961A3687E5CB498208C31DCB31BF54C66139EE8E04C06
SMDB:  c9991b3b69105a449e598c16eafac8dedc9c92e912b89ea5c9b90fdb03811066

Doom Port (PD) Jnmartin84.z64
ACB2AE61611D555152C105B21CDF4395ABB81C6AAC3E73A68F62EFA206B43920
SMDB:  76b9b2fd717fd07478ffdf81bec2d9cf4e53563a8adcbc5b988df41673f1e222

LoZ Ocarina of Time - Play as Ganondorf (Hack) v1 XModxGodX.z64
58F5E657F61EBE6D2069E206FFD2C11F0DF944384BB09D5613F88544A5BA9907
SMDB:  275bb7d592f50ef7514858daad3d353b8b5cfa02708ca8f74e206473d7b447dc

**Comment by Drakonas** [comment]
The Controller Test Tool has since been updated and the Doom Port/Ganondorf hacks seem to be using unknown version I have been unable to find. I already have a WIP PR that I am working on submitting. Stay tuned.

**Comment by Infinitum8t** [comment]
Good call. Big Endian completely skipped my mind there. :P

Appreciate all your effort, along with your speedy response to the issues brought forth. :)

**Comment by Drakonas** [comment]
Is there a reason this was closed before the PR was pushed?

**Comment by Infinitum8t** [comment]
The mistake was mine. I misunderstood how this works. It's reopened.
