### ISSUE TITLE
MD/Genesis: Incorrect hash for Phantasy Star III - Generations of Doom Translation

### ISSUE THREAD

**Issue by bandit721** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#535]
Phantasy Star III - Generations of Doom (U) T+Eng, Parallax, FastWalk v1.2 Peaches.md

SMDB:  d69177506ac282c63741ffe6b06daae8853308ef4490f1aa3b001a2e44a57444
Correct: 51E33D9236485E1A069D5013B8EDDD66FEF6299EE81BB362E579E70EB82704E3

The instructions for applying the translation patch state that you must run the "Fix Checksum" utility as a last step if you're also applying both hacks/mods (parallax scrolling and fast walk) after applying the translation patch.  The hash listed in the DB is the hash prior to running the Fix Checksum utility.  The correct hash listed above is the updated hash after running the utility.  

Btw, the rom won't boot if the utility isn't run (checksum isn't fixed).  It just locks on an all red screen.

**Comment by tjanas** [comment]
@bandit721 this is fixed. Thank you for reporting this.
