### ISSUE TITLE
SNES: Update Bahamut Lagoon translation (rc8 -> 1.0)

### ISSUE THREAD

**Issue by Infinitum8t** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#542]
Bahamut Lagoon (J) T+Eng rc8 Near.sfc
-the rc8 file is no longer accessible from near's site or found anywhere else.
Bahamut Lagoon has been updated to v1.0 as of Feb/09/21.

**Comment by frederic-mahe** [comment]
And v1.1 since Feb/12/21 :-)

**Comment by frederic-mahe** [comment]
I wonder what was fixed, I don't see any changelog.

**Comment by tjanas** [comment]
> I wonder what was fixed, I don't see any changelog.

Unfortunately he didn't seem to provide a changelog with any of his prior updates.

**Comment by tjanas** [comment]
@Infinitum8t this is now fixed (updated to v1.1).
