### ISSUE TITLE
Duplicates in the Mega EverDrive SMDB (alphabetical folders)

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#58]
Those cases are tricky. On one hand, some users may be accustomed to one (erroneous) form of the name and would not be able to find the game under its correct name. On the other hand, there should be only one correct name for each game (title screen as suggested by @Jayde6?).

Good luck with that :-)

```
238ce3580bea34ede9ae5fb59263d822ed9400baaee6b402ed3370bebd1203c1	Mega EverDrive/1 US - G-P/Lightening Force - Quest for the Darkstar (USA).md
238ce3580bea34ede9ae5fb59263d822ed9400baaee6b402ed3370bebd1203c1	Mega EverDrive/1 US - Q-Z/Thunder Force IV - Lightening Force - Quest for the Darkstar (USA).md

567eb80a69ca1fea67f4cb64252e6a23e9bd41c3f9c4c422a6bc04dfb763509d	Mega EverDrive/3 Sega 32X/1 US - A-Z/Amazing Spider-Man - Web of Fire (USA).32x
567eb80a69ca1fea67f4cb64252e6a23e9bd41c3f9c4c422a6bc04dfb763509d	Mega EverDrive/3 Sega 32X/1 US - A-Z/Spider-Man, Web of Fire (USA).32x

75dd7e0c182a759a7e5beabbca7581ff11336c416fa4711804cf6f148fbc45c0	Mega EverDrive/1 US - G-P/Mortal Kombat 3 Ultimate (USA).md
75dd7e0c182a759a7e5beabbca7581ff11336c416fa4711804cf6f148fbc45c0	Mega EverDrive/1 US - Q-Z/Ultimate Mortal Kombat 3 (USA).md

95d7efb98e97f4ffffe68257aef9a855034a36a41b86cf9d332d129f30cb2d4b	Mega EverDrive/1 US - A-F/Bare Knuckle - Ikari no Tetsuken ~ Streets of Rage (World) (Rev A).md
95d7efb98e97f4ffffe68257aef9a855034a36a41b86cf9d332d129f30cb2d4b	Mega EverDrive/1 US - Q-Z/Streets of Rage - Bare Knuckle - Ikari no Tetsuken (World) (Rev A).md

d626a322b72bd0291207315649067a1579206cf6ca263e64636914fdb8f78fed	Mega EverDrive/2 Japan - A-Z/Japan - A-O/Mega Man Wily Wars - Rockman Mega World (Japan).md
d626a322b72bd0291207315649067a1579206cf6ca263e64636914fdb8f78fed	Mega EverDrive/2 Japan - A-Z/Japan - P-Z/Rockman - Mega World (Japan).md

e9f9c6f4c6460be142096b0f165251696b7188fc141f02db4af7272d1f5a7c5d	Mega EverDrive/2 Japan - A-Z/Japan - A-O/Demon Hunter Mamono Hunter Youko - Dai 7 no Keishou (Japan).md
e9f9c6f4c6460be142096b0f165251696b7188fc141f02db4af7272d1f5a7c5d	Mega EverDrive/2 Japan - A-Z/Japan - A-O/Mamono Hunter Youko - Dai 7 no Keishou (Japan).md

f06923767cc4e5e473e9b4260dd006fdbc76d090360ce3a3c21aa486555ecf44	Mega EverDrive/2 Europe - A-Z/1 PAL - M-R/Populous II - Two Tribes (Europe).md
f06923767cc4e5e473e9b4260dd006fdbc76d090360ce3a3c21aa486555ecf44	Mega EverDrive/2 Europe - A-Z/1 PAL - S-Z/Two Tribes - Populous II (Europe).md
```

**Comment by Jayde6** [comment]
They sure don't make it easy in some cases. What about a changelog? That way if they were confused they could see what titles were chosen and why. Luckily once everything is sorted out there shouldn't be a need to shake things up like this again.

     Lightening Force - Quest for the Darkstar (USA).md

US title, though title screen is just Lightening Force

     Mega EverDrive/3 Sega 32X/1 US - A-Z/Amazing Spider-Man - Web of Fire (USA).32x
     Mega EverDrive/3 Sega 32X/1 US - A-Z/Spider-Man, Web of Fire (USA).32

Box has the amazing part and its actually The Amazing not just amazing, title screen is just the second one

     Mega EverDrive/1 US - Q-Z/Ultimate Mortal Kombat 3 (USA).md

Box, copyright and title screen use this one

     Mega EverDrive/1 US - A-F/Bare Knuckle - Ikari no Tetsuken ~ Streets of Rage (World) (Rev A).md
     Mega EverDrive/1 US - Q-Z/Streets of Rage - Bare Knuckle - Ikari no Tetsuken (World) (Rev A).md

Just like with Lightening Force it has other region titles appended on to it, should just be Streets of Rage for the US folder

     Mega EverDrive/2 Japan - A-Z/Japan - P-Z/Rockman - Mega World (Japan).md

Is the proper title for the Japan folder

     Mega EverDrive/2 Japan - A-Z/Japan - A-O/Mamono Hunter Youko - Dai 7 no Keishou (Japan).md

No english on cover, possible partial translation of title tacked on for the other one

     Mega EverDrive/2 Europe - A-Z/1 PAL - S-Z/Two Tribes - Populous II (Europe).md

Box and title screen are this

**Comment by SmokeMonsterPacks** [comment]
Thanks for these. I remember creating the dupes in response to error reports, since people thought the ROMs were missing, I'd create a dupe with the common name. I'm going to leave these for now, but may eventually purge them.
