### ISSUE TITLE
Duplicates in the Super EverDrive SMDB (alphabetical folders)

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#59]
```
1735f790ebcfa1bed2430aecde3abaf24c88ff99aa0186736f8f36b674bc9350	SD2SNES/1 US - F-M/Garry Kitchen's Super Battletank - War in the Gulf (USA) (Rev 1).sfc
1735f790ebcfa1bed2430aecde3abaf24c88ff99aa0186736f8f36b674bc9350	SD2SNES/1 US - S/Super Battletank - War in the Gulf (U) (V1.1) [!].smc

32d0f1ca5b91fd9b2caf81422fb9e8fb30bc091f0b2a429b9269dd307fcba4fd	SD2SNES/1 US - S/Spawn (U) [!].smc
32d0f1ca5b91fd9b2caf81422fb9e8fb30bc091f0b2a429b9269dd307fcba4fd	SD2SNES/1 US - T-Z/Todd McFarlane's Spawn - The Video Game (USA).sfc

3cdebbd8adc4bb6773a7995f542fdac49adefca71cba583255a1c1bf37ac3946	SD2SNES/1 US - A-E/Dr. Mario & Tetris (USA).sfc
3cdebbd8adc4bb6773a7995f542fdac49adefca71cba583255a1c1bf37ac3946	SD2SNES/1 US - T-Z/Tetris & Dr. Mario (USA).sfc

64bc4707f422661a66618088887e2363a5f896ea683c58984fffd96dd21ab5f0	SD2SNES/1 US - N-R/New Horizons (USA).sfc
64bc4707f422661a66618088887e2363a5f896ea683c58984fffd96dd21ab5f0	SD2SNES/1 US - T-Z/Uncharted Waters - New Horizons (U).smc

7da4a3cfa5de4bb4722a6e2a42c26aae322b5e668f1645d8c870fb99e6080600	SD2SNES/1 US - S/Secret of the Stars (U).smc
7da4a3cfa5de4bb4722a6e2a42c26aae322b5e668f1645d8c870fb99e6080600	SD2SNES/1 US - T-Z/Tecmo Secret of the Stars (USA).sfc

8049175767eddbc3e21ca5b94ee23fc225f834ccfab4ded30d2e981b0ef73ab6	SD2SNES/1 US - A-E/Adventures of Yogi Bear (USA).sfc
8049175767eddbc3e21ca5b94ee23fc225f834ccfab4ded30d2e981b0ef73ab6	SD2SNES/1 US - T-Z/Yogi Bear (U) [!].smc

b72fbbfe737eff49f59dcef9f13b963e50c5bc322d7eb0e7b4c25f3a71aa0815	SD2SNES/1 US - S/Spider-Man & Venom - Separation Anxiety (U).smc
b72fbbfe737eff49f59dcef9f13b963e50c5bc322d7eb0e7b4c25f3a71aa0815	SD2SNES/1 US - T-Z/Venom-Spider-Man - Separation Anxiety (USA).sfc

2ec71aca4efc3791b6b3e65956df3eafd2a46e223d5ea71aead07d30ca48b6c9	SD2SNES/2 Europe - A-Z/PAL - A-J/James Pond 3 - Operation Starfi5h (Europe).sfc
2ec71aca4efc3791b6b3e65956df3eafd2a46e223d5ea71aead07d30ca48b6c9	SD2SNES/2 Europe - A-Z/PAL - K-R/Operation Starfi5h (Europe).sfc
```

**Comment by Jayde6** [comment]
SD2SNES/1 US - F-M/Garry Kitchen's Super Battletank - War in the Gulf (USA) (Rev 1).sfc

Box, and Title screen are this one

     SD2SNES/1 US - S/Spawn (U) [!].smc
     SD2SNES/1 US - T-Z/Todd McFarlane's Spawn - The Video Game (USA).sfc

Tough call, box and cart use the second one but the title screen just says Spawn

     SD2SNES/1 US - T-Z/Tetris & Dr. Mario (USA).sfc

Box and title screen both use this one, the tile screen cycles between the two but starts with this one first

     SD2SNES/1 US - T-Z/Uncharted Waters - New Horizons (U).smc

Unusual one, box does not have the uncharted waters part but cart and manual do. It also shows up as a splash screen before just displaying New Horizon

     SD2SNES/1 US - T-Z/Tecmo Secret of the Stars (USA).sfc

Box and title screen have Tecmo in the title

     SD2SNES/1 US - A-E/Adventures of Yogi Bear (USA).sfc
     SD2SNES/1 US - T-Z/Yogi Bear (U) [!].smc

Same deal as Spawn, box and cart say adventures of, title screen doesn't

     SD2SNES/1 US - T-Z/Venom-Spider-Man - Separation Anxiety (USA).sfc

Box, front of cart and copyright screen use this one though the title screen and top label of cart just use Separation Anxiety

     SD2SNES/2 Europe - A-Z/PAL - A-J/James Pond 3 - Operation Starfi5h (Europe).sfc
     SD2SNES/2 Europe - A-Z/PAL - K-R/Operation Starfi5h (Europe).sfc

Another one where box and cart are just Operation Starfi5h but the title screen uses the James Pond part

**Comment by SmokeMonsterPacks** [comment]
No need to look too far into any of the title questions. Whenever there's a issue, I will opt to use No-Intro's filename. That won't be the best option, but it will at least standardize things and makes it much easier for me to update when No-Intro puts out new sets.

**Comment by Jayde6** [comment]
Completely understandable unfortunately. I've seen some of these same errors frederic-mahe has been finding in their naming schemes as well. I guess that's part of the beauty of these lists though, is that anyone can download them and alter them to their own liking, changing stuff where they want. I can't imagine the workload to update all these lists when they update their sets. If you need any help organizing wise let me know.

**Comment by frederic-mahe** [comment]
Maybe some of the duplications we observe come from No-Intro? If it is the case, we can signal them what we've found and see if the problem can be solved upstream. We don't have much to loose in trying. @SmokeMonsterPacks do you know how to contact the admins there? I have no idea how the No-Intro community is organized.

**Comment by Jayde6** [comment]
Not the duplication, at least not that I've seen but the naming.
For instance they have Streets of Rage as "Bare Knuckle - Ikari no Tekken ~ Streets of Rage (World) "

Looking at it though it seems to be an effort on their part to avoid duplicates as that is the world rom, so there is no listing for a US rom with just the US title.

I've gone back and checked a handful of the entries listed recently where their are title confusion and it seems that most of them are labeled the same as my suggestions, so I'm not as concerned anymore. I remember looking on there a while ago and the naming on stuff seemed all over the place, thankfully it looks a lot better now.

**Comment by SmokeMonsterPacks** [comment]
@frederic-mahe No, I'm not in communication with No-Intro. Most of these naming issues are on my end though and are left-overs from the Good (sets) days. 

When I'm back from traveling in late July I will probably do some work streams where I start to tackle the dupes. It looks like this is really going to make an improvement overall and tidy things up. Your new script fixes a lot of things that have slipped under my radar for a few years.

**Comment by SmokeMonsterPacks** [comment]
OK, these are all fixed for the next update. Another huge thank you for the help @frederic-mahe!!
