### ISSUE TITLE
Feature Request: No Output and Directory Names in Missing.txt

### ISSUE THREAD

**Issue by Jayde6** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#60]
Would it be possible to have these two things added as features?

If someone were just wanting to see what they were missing it would be great to have it generate a missing.txt only without going through the whole output process.

Directory names in the missing file would help towards knowing what exactly was missing (type, region, etc).

**Comment by frederic-mahe** [comment]
Hi @Jayde6 

to compare your ROM set with the target ROM set (SmokeMonster's) implies to compute hashes for all files, there is no other way. Now, you don't need to `build_pack.py` again to get a list of missing ROMs, you can perform that comparison with `parse_pack.py` and some text comparison tool, as described in the [wiki](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/wiki/How-to-build-and-maintain-packs):
- use `parse_pack.py` on your own organized ROM set to create a DB file,
- compare your DB file with SmokeMonster's,
- get a list of what's missing in your ROM set (including directory names)

I hope this answers your questions.

**Comment by frederic-mahe** [comment]
Alternatively, @kraqh3d has an `audit_pack.py` script that does this. And @coughlanio had a set of tools to manipulate SMDB files (but the repository does not seem to be available anymore).

**Comment by Jayde6** [comment]
I see, I realized it would have to compute the hashes for all files, I thought maybe there might be a way to do it without the output part of the command. I'll definitely check out that audit_pack.py and the wiki, thanks for the info.

**Comment by frederic-mahe** [comment]
With the `build_pack.py`, you can also redirect the output to `/dev/null` (on Unix/linux system).
