### ISSUE TITLE
Super EverDrive & SD2SNES SMDB corrections (as reported by Jayde6)

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#66]
initially reported by @Jayde6 in issue #38

*wrong section*

	SD2SNES/1 US - S/Super Bomberman 4 English (J) T+Eng.smc
	SD2SNES/2 Japan - A-Z/Japan S-Super Final/Super Double Dragon Trained (Hack).sfc
	SD2SNES/2 Japan - A-Z/Japan S-Super Final/Sunset Riders Trained (Hack).sfc

*there is a Rev 1 in that folder already*

	SD2SNES/2 Other Regions - A-Z/Germany/Terranigma (Germany).sfc

*Prototype listed in main folder*

     SD2SNES/1 US - A-E/Batman - Revenge of the Joker (U).smc

**Comment by SmokeMonsterPacks** [comment]
Excellent, these will all be fixed in the next update!
