### ISSUE TITLE
proposal for the organization of the Everdrive N8 pack

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#75]
After studying the mapper support for the PowerPak, Everdrive N8 and jailbroken Nt mini, I would like to suggest the extension of the `Unsupported Games` section of the pack. Other suggested changes should be in line with what @SmokeMonsterPacks mentioned lately in his weekly stream.

All _official_ roms (No-Intro) are distributed in the first sections of the pack:
```
1 US - A-F/
1 US - G-Q/
1 US - R-Z/
2 Europe - A-Z/
2 Japan - A-Z/
2 Unlicensed - A-Z/
3 Famicom Disk System/
3 Nintendo VS. System Arcade/
3 PlayChoice-10 Arcade/
4 Betas, Prototypes, Revisions/
4 Game Series Collections/
```
A ROM is accepted in the following sections if one can use a PowerPak or an Everdrive N8 to run it on a real NES/Famicom, or if it runs on a jailbroken Nt mini:
```
4 Hacks/
4 Homebrew/
4 Translations/
5 Tools & Service Test Carts/
```
As an incentive for flashcart/core makers, a selection of unsupported games are listed for each system (PowerPak, Everdrive N8 or jailbroken Nt mini). Mappers play a key role in game support, so it makes sense to sort games by mapper:
```
Unsupported Games - N8/
Unsupported Games - N8/Sort By - Mapper/
Unsupported Games - Nt mini/
Unsupported Games - Nt mini/Sort By - Mapper/
Unsupported Games - PowerPak/
Unsupported Games - PowerPak/Sort By - Mapper/
```
The lists of unsupported games should be short for the N8 and the Nt mini. It might be much larger for the PowerPak. So, should we include the PowerPak or not?

**Comment by SmokeMonsterPacks** [comment]
This was extremely helpful. I've included the basics of this layout in the next update (v6.2), except that I am keeping the NT Mini files separate in the Jailbreak pack. Thanks @frederic-mahe!
