### ISSUE TITLE
Certain Ttiles only appear in the Game Series Collection for SNES

### ISSUE THREAD

**Issue by Ryan-Myers** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#77]
There are many games in the SNES pack, that only appear in the "4 Game Series Collections". This means that people looking for them in the expected places (e.g."4 Translations") might not find them. I have a list below. These should probably be moved to other directories as well.

- 004 Final Fantasy VI (J) [T+Eng1.2_RPGOne][h1] (All Fixes).smc	9fc6f2a12baae59ab3091cc452443f366fe72643e4b9709710b2e74b1d1feffd
- 020 Final Fantasy V (J) [T-EngX.X_RPGe].smc	04e43a75f491a79d408a315fd68a026371387381fc7c4597e2acb9a44758549f
- 086 Live A Live (J) [T-EngX.X_AGTP].smc	b561a2b91887dcd849a77e9667e30c1c22acc6606e87ade75ea59065077d2807
- Aladdin [BR].smc	82b8b0961b635c91bdd852c9dd871b473b63ea027834f9e15bb93ae21b15f035
- Alien 3 (E) [BR].smc	2e98dc8df21d51c7c9fcedeac1eb1a01600600049d0fcc3c7ef84cf72cd2d37e
- Alien vs Predator (u) [BR].smc	55c763724b8de7c15d7097688a09453a92e5c6013d0efa3765006dc22c20515a
- BS Chrono Trigger - Music Library (J) [T+Eng1.00e_Terminus].smc	14b5d74e79c7e6d9cbb2417b97af1275581f8dc9685253f7da67b72db8ea051f
- BS Dr. Mario (J).smc	e3cfb163c46e59e555f8be43148797cafab572d44a1e43d06244361797b105ac
- Chrono Trigger Uncensoring+Bug Fix (Hack) Final++ Chronosplit.smc	249411948b9e8c2712f24510b1d477392ded2e3390cb738f933e931569385279
- Corn Buster (Europe) (Proto).sfc	61af30c3be855c5cea005bd3bd13c5cd626904f468597c73f886064136949e1d
- Demon's Crest (U) [T-Por].smc	5748fc40b9d9f2a9cc4d0a105c004cf8f607c54458ae57381c1b6473ffd524d0
- Dezaemon - Kaite Tsukutte Asoberu (Japan) T+Eng1.0_AGTP.smc	069e1bd3e732d3c87e35f1dd005a3d6d1d917bfc68bc87bd4b8e6b69bf2de1e5
- Donkey Kong Country 3.SMC	ab5d524163293a98ed52447a761f96bd84daeaf07f3c67b2d9bc2110b9d4b402
- Dragon Ball Z - Hyper Dimension (J) [o1][T+Eng1.1_SS4Squall].smc	fa6c237b1da546555d7176370470cbbd38fce8be58b423a49b20e48427b6955a
- Dragon Ball Z - Super Saiya Densetsu (BR).smc	dac119381dbf8536e903ce2c6786e673b362190de01ed1a34082ae3505b0304c
- Dragon Quest VI - Maboroshi no Daichi (J) T-Eng DeJap.smc	a2c068a03379390258e638516b513e266a0881ea9c6345224f3cc22165153461
- Final Fantasy VI Uncensored (hack) v1.94 Woolsey Only Rodimus Primal.smc	4904d2584710c3af5a13efdc4874f6f8921210eb30ee731eb4115b1a310e7ee9
- Final Fantasy VI Uncensored+ (hack) v1.94 Fix+Opera+MenuMusic+AddOns Rodimus Primal.smc	2e0dd8f13c884608ebd69295e7e6fa157ec00557ee84c3eded138ea591813c8d
- Final Fight Guy (BR) v0.98.smc	d568cd3f5c0715336b597b9349dc68638ea3706304dde99e503c1d2361598587
- King of Fighters 2000 (Brazil) (Unl) (Pirate).sfc	e8b74960a80453cf052519a43895fa54b635448db6a95aabe4986bb152c6e170
- Legend of Zelda, A Link to the Past (BR).smc	fd7e0a94b69e705dc1c7f4ac71618f193b31d5d66f8a38a0022489003f6de9c4
- Lucky Luke (Europe) (En,Fr,De,Es).sfc	db1013db6cb3158fe35f1f004d15a3df3b93a0c683fa1a6446610cca7a54e917
- Mega Man 7 (U) [BR].smc	0539c0199467eb5af05bd1a940bb7d2f7e67c5884a836c028e59ec05f6977b69
- Mickey to Donald - Magical Adventure 3 (J) [T+Eng1.0RPGone].smc	1295a0973c1d57d0e95d9dcae16c9d20a2c7acd6cb63280d2705ea190bff0884
- Mr. Bloopy - Saves the World (USA) (Proto) (1994-06-21 Level 11-G).sfc	249d966aac41608dd2edcd5a93fd877144648cc5939fa50f66cded381269c179
- Mr. Bloopy - Saves the World (USA) (Proto) (1994-06-21 Levels 000).sfc	0bb4b7301a2773831136b3f39e7c841551570865b9f856b1f26ca78e0b8d358d
- Mr. Bloopy - Saves the World (USA) (Proto) (1994-06-22 Levels-B).sfc	40cff9170eb142a50bef5df9859ce2761a185250d2a3c174251ccce8e5d59c96
- Mr. Bloopy - Saves the World (USA) (Proto) (1995-02-16).sfc	4a018f866be9bcd844f36ee4ce5408ba4c2834acd9a9d4143bb326c6cd261bfb
- Nightmare Busters (Europe) (Proto).sfc	620af60cd4a6683871e9339c2db63d87538819af29b3cf967a1729b53a3bd6b3
- Ronaldinho Soccer 98.smc	1ba47d119032cf93254a443db6168de5eb886139cc07a160d7d5512e0a749d07
- Rudra no Hihou (J) [T+Eng.99b2_AGTP].smc	aae0ad8ae760793ba5903f169d0e06e036a63f8009121e6fa4163ae9cc9b4b82
- Sailor Moon Super S - Floating Panic (J) T+Eng v1 Dynamic-Designs.smc	3dbfd2c9a0ccf443b6adb70bd1f0d2dd61d8205d656966755fdd256cff068c16
- SpellCraft - Aspects of Valor (USA) (Proto).sfc	2858cfc8b6cd138c69fbf59597d5bacaeb380ec7f284629f98e0a83642f90dfd
- Super Castlevania IV (U) [BR].smc	11608b8dd6e29ad4f422eb6356c5d9bc02b4118b8a4c955836d11eee3c687086
- Super Gachapon World - SD Gundam X (Japan) (Translated En).sfc	43cf145529d8f73a3e6664e2ae091d65696d74e5521d5e5b1174070a150f7012
- Super International Cricket (Europe).sfc	e1b3f7d77431faf0064a9fec51a43c196088681c23e9c4182ef436ae2870456f
- Super Mario World (U) [BR].smc	020b94187f4ff7f29670f8e894136d5ec326ec1430725616354da3233637c6c4
- Super Puyo Puyo 2 (J) T-Eng v1.1 J2e.smc	fd27261349e2d4baf726348d1cb8367f259ebe1ef6a6174914d2c7420a826ce2
- Taekwon-Do (Korea).sfc	e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
- Tintin - Prisoners of the Sun (Europe) (En,Fr,De,Es).sfc	4be853af44dbb77fde806ffe20d9e25b52e51684e7d351df5164cd4c2c71ae82
- Tintin in Tibet (Europe) (En,Fr,De,Nl).sfc	f41e96c38cc6f2e06ae54f4727bf38ae894cb38ce5fe8e0f59436a625c25fab1
- Worms (Europe).sfc	1d29ee4be2ea2807858bb04730e33f24ebce62a23bb95256766d98824cc7a59e
- Wrecking Crew '98 (J) T+Eng v1 ShadowOne333.sfc	2037fd0466dd802ff136f0987c5865f52b3a25fc0916843f0d848fd68687d249

**Comment by FiZiX** [comment]
I also suspect this is a bad dump or is mislabeled because I can't find references to it anywhere on the internet:

`BS Dr. Mario (J).smc	e3cfb163c46e59e555f8be43148797cafab572d44a1e43d06244361797b105ac`

Why not just use the no-intro version?

**Comment by SmokeMonsterPacks** [comment]
I don't maintain the Game Series Collections and I want to avoid supporting them myself since it would initiate a flood of issues. The reason these ROMs are unique to the GSC is because they are all outdated versions and the core list has moved on to updated ROMs.
