### ISSUE TITLE
errors in the N8 pack

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#8]
Bort from epforums.org reports a couple of errors in the N8 pack:

> Why are there extra copies of Galactic Crusader (USA) (Unl).nes and King Neptune's Adventure (USA) (Unl).nes in the 2 Unlicensed - A-Z/1 Unlicensed L-R directory? Those games don't begin with a letter between L and R.

> Also, why does the 3 Nintendo VS. System Arcade directory contain one of the roms from the NT Jailbreak database (VS. TKO Boxing - NT Fixed (VS) NES Patched v0.9b [FIX] Morgan Johansson, NT v1 SmokeMonster.nes)?

**Comment by frederic-mahe** [comment]
The first one is solved by [Quantum-cross pull-request](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/pull/4).

**Comment by SmokeMonsterPacks** [comment]
Thanks. Those are just missorted, I'll have them fixed. 

The NT Fixed rom is included there because that same NT Fix made it N8 compatible as well, so I included it :)
