### ISSUE TITLE
Duplicate with different hash SD2SNES SMDB

### ISSUE THREAD

**Issue by CruelTott** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#81]
I was looking through the list for files with the same name but with different hashes and found these two files.

> SD2SNES/4 Betas, Prototypes, Revisions/Betas/Beta A-M/King Arthur's World (USA) (Beta).sfc
> SD2SNES/4 Betas, Prototypes, Revisions/Revisions/USA/King Arthur's World (USA) (Beta).sfc

When I compared them the only differences I found is that the second one has replaced the text
> Jaleco USA

in a credits section,  with the text:

> QUARTEX!!!

and also changed the last section of the file from a bunch of
> 0xFF

bytes to a repeating string of

> QUARTEXQUARTEXQUARTEX

Quartex seems to be a pirate group.

In my opinion there is no need to have both these roms in the list.

**Comment by tjanas** [comment]
@CruelTott fixing this
