### ISSUE TITLE
Formatting issue in MiSTer db

### ISSUE THREAD

**Issue by coughlanio** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#83]
```
Traceback (most recent call last):
  File "build_pack.py", line 151, in <module>
    db, num = parse_database(TARGET_DATABASE)
  File "build_pack.py", line 76, in parse_database
    for line in target_database:
  File "/home/chris/.pyenv/versions/3.7.1/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2291: invalid start byte
```
I ran some of my own scripts on the MiSTer pack DB, and ran into some issues. Passed it through the `build_pack` script and it looks like that there's some Windows encoding that made it in. Not sure what the policy is, but I'd suggest keeping everything UTF-8.

Changing `parse_database` to `with open(target_database, "r", encoding="windows-1252") as target_database:` resolves the issue.

**Comment by frederic-mahe** [comment]
Hi @coughlanio , could you please locate the culprit file (or files)?

**Comment by frederic-mahe** [comment]
Found it!
```
MiSTer/C64/Music - [PRG]/A-N/+�glejazz (1990)(Panoramic Designs).prg
```
Can you fix it upstream @SmokeMonsterPacks ?

**Comment by SmokeMonsterPacks** [comment]
Got it, let me reparse and re-upload it. Thanks for the help!

**Comment by SmokeMonsterPacks** [comment]
Fixed, hopefully :D

**Comment by frederic-mahe** [comment]
Perfect, there were no other problematic filename. The build_pack script works correctly now.
