### ISSUE TITLE
Atari 2600 SMDB file starts with four tabulations

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#85]
Hi @SmokeMonsterPacks 

for some reason (manual editing after `parse_pack.py` maybe?), the SMDB file for the Atari 2600 starts with a line of empty fields. The `build_pack.py` script chokes on that, and users cannot build the Atari 2600 pack. I've pushed a temporary patch, but could you please pull my changes, regenerate that SMDB on your side and push it?

Thanks,

By the way, that's the only affected SMDB file.

**Comment by SmokeMonsterPacks** [comment]
Thanks, I think that I just fixed it.
