### ISSUE TITLE
Feature suggestion: Pack dependencies

### ISSUE THREAD

**Issue by coughlanio** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#89]
Playing around with the MiSTer pack, and the way it has placeholders for the Everdrive Packs, I was wondering if we could possibly decide a format that will allow specifying dependencies that can let you build out the MiSTer pack with all the EverDrive files pre-populated. This could also be useful for the Mega Everdrive pack importing Master System etc.

The parser could handle this gracefully, if the SMDB doesn't exist, just ignore - and possible we can have it ignore by default, and add a build flag such as `--with-deps`?

Maybe something like `#include "EverDrive GB SMDB.txt" "Gameboy";` at the top of the file? (The first quotes being the SMDB file to include, the second being the relative directory to write the files to).

I'd be happy to work on it, if you think it'd be a feature worth having (I know it would help my workflow for sure).

**Comment by frederic-mahe** [comment]
@coughlanio You would need to edit the MiSTer SMDB file in order to do that. Since there is some editing involved, maybe a batch file would be more appropriate and flexible when building nested packs?
