### ISSUE TITLE
Maybe Internet Archive would be interested in preserving these packs?

### ISSUE THREAD

**Issue by jan-kleks** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#9]
Well, they preserve all kinds of stuff.

Regards and keep up good work!

**Comment by frederic-mahe** [comment]
If you mean preserving the ROM packs, they are already mirrored by the Internet Archive. The link is somewhere on the EPforum "EverDrive Packs Release Thread".

If you are talking about the text files describing the ROM packs, git makes it easy to share and to preserve them. I would say that the risk of loosing them is small now.
