### ISSUE TITLE
OS Specific Files in STV Pack

### ISSUE THREAD

**Issue by coughlanio** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#93]
```
Darksoft STV/@STV Roll-Up Pack/@STV Roll-Up Pack.7z.tmp
Darksoft STV/@STV Roll-Up Pack/System Volume Information/IndexerVolumeGuid
```

**Comment by frederic-mahe** [comment]
That should be fixed for future packs with commits https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/1990463f8fc8720b6b1aa6fff73d52e6ef2a7c71 and https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/a09c7d3fa811fd067d9b44e989a9bde57dc76f1a
