### ISSUE TITLE
Mega Man Battle Network 2 (USA) (Debug Version).gba is a bad dump

### ISSUE THREAD

**Issue by blathers16** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#952]
Hi, the version you have has the following md5 sum : 710e4ecb8f411648fedad9102c7b3b93
which according to no-intro is a bad dump.
https://datomatic.no-intro.org/index.php?page=show_record&s=23&n=2835

Here are the correct sums:
![image](https://github.com/frederic-mahe/Hardware-Target-Game-Database/assets/2584455/9997823a-5da1-4694-a4d4-79561bd70134)
Name: Megaman - Battle Network 2 (USA) (Debug Version).gba
Size: 8388608 bytes (8192 KiB)
CRC32: C3AABD70
CRC64: F340E3C9BB5921DC
SHA256: 075a077baa4e1810a2b018a1bf956e0bf8a7890b5c2caffe7a41ca59dad80f06
SHA1: d8968ac6c33f376d8f6ce6205b53756434a8d2ac
BLAKE2sp: 40f86bc3c62eeb92c2c2544a9f17ea1e20bc17d8bf64610c37e357272bc5de67
MD5: 62f96deebe82b3b3fddf29f0d433b006

**Comment by tjanas** [comment]
Thank you, it looks like it was identified as overdumped on 2022-11-08

**Comment by tjanas** [comment]
@blathers16 let me know if the above pull request looks good to you

**Comment by blathers16** [comment]
I will check it out when I get home, too much work to do on mobile.

**Comment by blathers16** [comment]
Hi, @tjanas that all looks correct.  Sorry it took so long to get back to you, I forgot about this.
