### ISSUE TITLE
Update SD2SNES pack with newly supported chips (GSU, SA1, SDD1)

### ISSUE THREAD

**Issue by mbarbero** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#98]
The alphabetical folders should include games with the newly supported chips:

* S-DD1 (since v1.10.0)
* SA-1 (since v1.9.0)
* SuperFX (since v1.8.0)

Currently, games using these chips are only listed in "3 Special Chip Games", "4 Betas, Prototypes, Revisions", "4 Game Series Collections" and "4 Hacks"

**Comment by mbarbero** [comment]
And while CX4 is supported for a while, games should be in alphabetical folders as well.

**Comment by mbarbero** [comment]
And finally SDD1 should be removed from the list of unsupported chips

**Comment by frederic-mahe** [comment]
thanks @mbarbero , sorry for the delay.
